### PR TITLE
Update add-link

### PR DESCRIPTION
**Pull request by firstads**
### Screenshot

<details><summary>Click to expand</summary>

</details>

### CODE REVIEW

**Comment by spirillen** [comment]
no descriptions provided

**Comment by firstads** [comment]
[image: image.png] this is orginal website idata.com.tr
[image: image.png] idaata.org fake scam page using cloaker

spirillen ***@***.***>, 17 Ağu 2023 Per, 19:03 tarihinde şunu
yazdı:

**Comment by spirillen** [comment]
I'm unable to access impersonated domain

image

While the one you reports as the phishing domain is protected by the MITM network of Cloudflares

This makes it hard to compare, any change you can generate a screenshot to me?

- `idaata.org`: https://0xacab.org/my-privacy-dns/matrix/-/issues/651663

**Comment by spirillen** [comment]
Found it via another source, but I don't see the similarity

image

**Comment by firstads** [comment]
[image: image.png] they are using cloaking system , only turkish ip address
and google search clicked redirect this page

spirillen ***@***.***>, 17 Ağu 2023 Per, 22:24 tarihinde şunu
yazdı:

**Comment by firstads** [comment]
and they say we are idata official

engine altan ***@***.***>, 17 Ağu 2023 Per, 23:05 tarihinde
şunu yazdı:

**Comment by firstads** [comment]
they using domain same like idata.com.tr they are using scam page idaata.org
rg/

engine altan ***@***.***>, 17 Ağu 2023 Per, 23:07 tarihinde
şunu yazdı:

**Comment by firstads** [comment]
this is mobile screenshot , they are always changing dynamic index  , they
say that " we are idata official " this is idata fake page , you cant see
this content because only turkish ip address , and google click

spirillen ***@***.***>, 17 Ağu 2023 Per, 23:17 tarihinde şunu
yazdı:

**Comment by spirillen** [comment]
try log in to github, your image attachments are not attacked via email

**Comment by firstads** [comment]
WhatsApp Image 2023-08-17 at 23 20 25
can you see ?

**Pull request merged**
