### PR TITLE
Update add-domain

### PR DESCRIPTION
**Pull request by Kehpry**
## Domain/URL/IP(s) where you have found the Phishing:

```
https://dofus-touch-com.fr/fr/mmorpg/actualites/news/breche-plantalia/
https://dofus-touch-com.fr/fr/mmorpg/actualites/news/breche-plantaniale/
https://dofus-touch-com.fr/fr/mmorpg/actualites/news/breche-volkanik/
```

`https://www-dofus-com.fr/es/mmorpg/actualidad/noticias/dimensi%C3%B3n-del-osatope/`

`https://wvww-papycha.fr/quetes/faille-volkanik/prerequis/`

## Impersonated domain

`dofus-touch.com`
`dofus.com`
`papycha.fr`

## Describe the issue

All domain names are used for phishing. URLs are regularly changed to avoid being suspended.

### Screenshot

<details><summary>Click to expand</summary>

</details>

### CODE REVIEW

**Comment by spirillen** [comment]
Can you post some screenshots from 

```
dofus-touch.com
dofus.com
```

All I see is Crimeflares fingerprinting trackware

image
image

**Comment by spirillen** [comment]
`wvww-papycha.fr`: https://mypdns.org/my-privacy-dns/matrix/-/issues/1164007
`dofus-touch-com.fr`: https://mypdns.org/my-privacy-dns/matrix/-/issues/1164006

**Comment by Kehpry** [comment]
Hi,
VPNs are prohibited, that's why you have this result.
Screenshots :
Screenshot 2022-09-04 at 22-23-45 Lance Dur une aventure transmédia - Info - Actualités - DOFUS Touch un MMO colossal à portée de doigt !
Screenshot 2022-09-04 at 22-24-20 2 65 l’heure du live approche

**Comment by spirillen** [comment]
I'm blocking [Crimeflare](http://crimeflare.eu.org/) as MITM have always been a bad idea, and I do not support tracking.

**Pull request merged**
