### PR TITLE
Update add-link

### PR DESCRIPTION
**Pull request by addliam**
Another element from #fakebard campaign

## Domain/URL/IP(s) where you have found the Phishing:

https://www.jas-per.life

## Impersonated domain

Jasper AI https://www.jasper.ai

## Related external source

Similar behavior to a hashtag called #fakebard even though #fakeai fits better.
Any Run Report (100/100) https://app.any.run/tasks/cb3f52ae-9fcb-4e74-9d09-f6d0aa605139

## Describe the issue

Rar file with password that load a malicious chrome extension

### Screenshot

<details><summary>Click to expand</summary>

</details>

### CODE REVIEW

**Comment by addliam** [comment]
Also, I would like to know what the process is after a PR like this is approved. Is this somehow connected to VT, because now there are security vendor flags (0/90)? I hope you can help me better understand the process.

**Comment by addliam** [comment]
@mitchellkrogza kindly remainder

**Comment by spirillen** [comment]
A couple of other subdomains I found in my own achieve https://0xacab.org/my-privacy-dns/matrix/-/issues/81703

```css
beta.jasper.ai
ref.jasper.ai
t.jasper.ai
```

**Comment by spirillen** [comment]
AS I can't find any activities regarding [jas-per.life](https://0xacab.org/my-privacy-dns/matrix/-/issues/642834) I'm going to close this PR. IF/WHEN you find any evidence this should have been reactivated and therefor active, please reopen/Ping for renewed actions

--------------------------

> @mitchellkrogza kindly reminder

Ping @spirillen and do it on https://0xacab.org/my-privacy-dns/matrix or @spirillen@ioc.exchange / @JerryMouse@infosec.exchange there you'll have better luck :smile: you could also try https://matrix.to/#/#mypdns:matrix.org

This is because I'm the most online, and of curse serving my own project the most.

> Also, I would like to know what the process is after a PR like this is approved. Is this somehow connected to VT, 

1. The VT project is importing the https://github.com/mitchellkrogza/phishing.Database
2. phishing.Database is importing the manual added records from this repo

> because now there are security vendor flags (0/90)? I hope you can help me better understand the process.

VT will not add any records from https://github.com/mitchellkrogza/phishing* higher than a yellow warning level.

------------

**Pull request closed without merging**
