### PR TITLE
add-domain bangladesh-railway.com

### PR DESCRIPTION
**Pull request by arman-arif**
This domain is phishing the original website https://eticket.railway.gov.bd

## Phishing Domain/URL/IP(s):
bangladesh-railway.com

## Impersonated domain
eticket.railway.gov.bd

## Describe the issue
https://eticket.railway.gov.bd is the website where you can book train tickets online in Bangladesh. https://bangladesh-railway.com is phishing that website. When someone searches on Google for booking train tickets in Bangladesh this phishing website (https://bangladesh-railway.com) comes first in the search results. And when they go to this phishing site and book a ticket they get scammed and their money is lost forever. Please add it to the phishing list.

### Screenshot

<details><summary>Click to expand</summary>

</details>

### CODE REVIEW

**Comment by spirillen** [comment]
Can't access `http://eticket.railway.gov.bd/` to verify, please sent screenshots.

image

**Comment by g0d33p3rsec** [comment]
> Can't access `http://eticket.railway.gov.bd/` to verify, please sent screenshots.

I'm also hitting a geofence but seem to get a slightly more informative error.
https://urlscan.io/result/4b4ab722-ab27-44c9-9aca-5bfaa7a4664b/
image

compare with the reported site
https://urlscan.io/result/91f8add2-43ba-4ffc-a7a8-a8695827bed0/
image

though the disclaimer on the reported site seems to take care to make clear that it is not the official government site
image

on the other hand, the site does seem to be a bit suspicious.  Looking at VirusTotal, only Fortinet currently has it flagged but there are some outgoing links that look deceptive.
image
image

**Comment by spirillen** [comment]
I Need "the profs" of the phishing, as I had the success of accessing the reported domain, Then I would call it a pretty ordinary WordPress site, which topic and interest lies within the trains and railways of Bangladesh, The option for searching trains in the frontage seems more like and ordinary API call to a backend and maybe the profit a bit on this "service" to maintain their domain.

I don't find the smoking gun.

**Comment by g0d33p3rsec** [comment]
> I Need "the profs" of the phishing, as I had the success of accessing the reported domain, Then I would call it a pretty ordinary WordPress site, which topic and interest lies within the trains and railways of Bangladesh, The option for searching trains in the frontage seems more like and ordinary API call to a backend and maybe the profit a bit on this "service" to maintain their domain.
> 
> I don't find the smoking gun.

I agree.  The most I see is the possibly deceptive link to `eticketrailwaygovbd.com` compared to the official `eticket.railway.gov.bd`.

**Pull request closed without merging**
