### PR TITLE
Update falsepositive.list

### PR DESCRIPTION
**Pull request by devinroth**
**Domains or links**
Please list any domains and links listed here which you believe are a false positive.

https://existential.audio

**More Information**
How did you discover your web site or domain was listed here?
https://www.virustotal.com
1. Website was hacked: NO
2. Incorrectly marked as Phishing on Phishtank or OpenPhish? Not listed on either. 

**Have you requested removal from other sources?**
Please include all relevant links to your existing removals / whitelistings.
Already removed from CRDF, BrightCloud. Happy to provide more evidence if needed.

**Additional context**

:exclamation:

We understand being listed on a Phishing Database like this can be frustrating and embarrassing for many web site owners. The first step is to remain calm. The second step is to rest assured one of our maintainers will address your issue as soon as possible. Please make sure you have provided as much information as possible to help speed up the process.

**Send a Pull Request for faster removal**
Users who understand github and creating Pull Requests can assist us with faster removals by sending a PR to **mitchellkrogza/phishing** repository, on the falsepositive.list file
> https://github.com/mitchellkrogza/phishing/blob/main/falsepositive.list
Please include the same above information to help speed up the whitelisting process.

### CODE REVIEW

**Comment by devinroth** [comment]
What did I do wrong?

**Comment by devinroth** [comment]
Lol. As someone with a popular github repo, I completely understand the pain. My apologies. I guess I was just really annoyed that my website is falsely on the phishing list.

I’ll resubmit and sorry for becoming one of those users that I loathe.

**Comment by spirillen** [comment]
Nice to see the template filled out :smiley: 

A note to you: you might check out `Cluster25` as they mark the site as #phishing as well
Another note to you: You should make external links more visible to visitors, so they in advance knows they are routed to spyware/trackware.
Another note to you: You should update your no-privacy note to be clear about your are collection of user data

```bash
sed "s/We may also collect analytics from 3rd parties including Github, Facebook, and Apple according to their privacy policies./We do collect analytics from 3rd parties including Github, Facebook, and Apple according to their privacy policies./g"
```

--------

Aside from my notes, then I don't see any reasons for you be listed in the filters, so from my point of view you are clear to go, but, as usual, if it turns up in any logs that you do have a bad code somewhere, the status will change.

**Comment by devinroth** [comment]
Thanks. I have contacted `Cluster25` and am waiting to hear back. 

I'll update the privacy policy as you suggest. 

Can you give me an example of more visible links like you describe?

**Comment by spirillen** [comment]
> Can you give me an example of more visible links like you describe?

IE, the `Flash Metro` links to `https://apps.apple.com/app/apple-store/id1490359765?pt=120783146&ct=ExistentialAudioWebsite&mt=8`. This is "problematic" as users on none mouse devices, can't hovering their mouse above the link to see where it leads them. I'll suggest you add this info by text or another visual indicator like a icon, but personal, I would prefer a clear text link.

SwiftOCS: Links to `https://github.com/ExistentialAudio/SwiftOSC`, same as above.

and so on. I know this is "unpretty" and very none modern approach, but the only honest way to do things to my opinion

**Comment by devinroth** [comment]
Thanks. I’ll keep it in mind when I next update the website. I appreciate the feedback.

Devin

**Pull request merged**
