### PR TITLE
Update add-link `akademie-gesundheitpur.s3.ap-southeast-1.amazonaws.c…

### PR DESCRIPTION
**Pull request by WebworkrNet**
…om/akademie-gesundheitpur.html

`akademie-gesundheitpur.s3.ap-southeast-1.amazonaws.com/akademie-gesundheitpur.html`

## Domain/URL/IP(s) where you have found the Phishing:

`email spam`

## Impersonated domain

`postbank.de`

## Describe the issue

`Vorübergehende Kontosperrung DE-479587A`

```
Sehr geehrter Kunde, 


Dies ist eine automatisierte E-Mail, die Sie über tägliche Sicherheitsupdates informiert.

wir möchten Sie darüber informieren, dass Ihr Konto aus Sicherheitsgründen vorübergehend gesperrt wurde. Ihre Sicherheit hat für uns höchste Priorität, und wir bitten Sie daher, Ihre Identität zu bestätigen, um Ihr Konto so schnell wie möglich freizuschalten.

Um den Freischaltungsprozess abzuschließen, bitten wir Sie, Ihre Bankdaten zu überprüfen. Dieser einfache Vorgang dauert in der Regel nur 5-10 Minuten und ermöglicht es Ihnen anschließend, wieder uneingeschränkt auf Ihr Konto zuzugreifen.


[ Jetzt Identität bestätigen](https://akademie-gesundheitpur.s3.ap-southeast-1.amazonaws.com/akademie-gesundheitpur.html?raN=7qmgpwdy84cqzdsm7g9mw0em1t8krx&taB=64cafd60e12b4_64cafd6d16995)

Bitte beachten Sie, dass diese Maßnahme ergriffen wurde, um unautorisierten Zugriff auf Ihr Konto zu verhindern und Ihre finanziellen Transaktionen zu schützen. Wir bitten um Ihr Verständnis und Ihre Unterstützung bei der Gewährleistung der Sicherheit Ihrer Bankdaten.

Um Ihre Identität zu bestätigen und Ihr Konto freizuschalten, klicken Sie bitte auf den unten stehenden Button. Sie werden zu einer sicheren Webseite weitergeleitet, auf der Sie den Prozess abschließen können.

Sollten Sie Fragen oder Bedenken haben, zögern Sie bitte nicht, sich mit unserem Kundenservice in Verbindung zu setzen. Unsere kompetenten Mitarbeiter stehen Ihnen gerne zur Verfügung, um Ihnen weiterzuhelfen.

Wir danken Ihnen für Ihre Mithilfe und Ihr Verständnis.

Mit freundlichen Grüßen,

Post Bank AG Kundendienst
```

 

                                                              

### Screenshot

<details><summary>Click to expand</summary>

</details>

### CODE REVIEW

**Review by spirillen — COMMENTED** [review]
This domain redirects to `https://list-manage10.com/offersoso/?raN=undefined&taB=undefined` for me

In case it still leads to phishing site for you, can you please add a screenshot to this MR

**Comment by WebworkrNet** [comment]
For security reasons I did not call up the link. Based on the wording, I assumed it was a phishing email. Thanks for investigating. Then it was probably a false alarm or the domain is now pointing to a different destination. I also report spam mails to [Spamcop.net](https://www.spamcop.net). It is possible that action was taken on the basis of my report.

**Comment by WebworkrNet** [comment]
MR = merge request?

**Comment by WebworkrNet** [comment]
> > MR = merge request?
> 
> Yep, since the days of git's birth :gift: 

Thanks

**Comment by spirillen** [comment]
Your welcome

that's not a PR stunt :wink: 

never figured out, is this report still phishy or ?

**Pull request closed without merging**
