### PR TITLE
Add rtu.lv to falsepositive.list

### PR DESCRIPTION
**Pull request by rsokolovs**
## Describe the issue

We had issue with our home page www.rtu.lv where we had bad code for redirecting urls. It's corrected already a few weeks ago.
We created issue but no response so far - https://github.com/mitchellkrogza/Phishing.Database/issues/703
Hope this PR will help.

### Screenshot

<details><summary>Click to expand</summary>

</details>

### CODE REVIEW

**Comment by spirillen** [comment]
I understand this can be a big problem to your education center, but as I do not have access to the log files, and therefor can't say why you where flagged, I would request a more info on your own solution.

you can (P|D)M me on one of the following accounts if you do not want the information shared in public

@spirillen@matrix.rocks

https://matrix.to/#/@spirillen:matrix.org

**Comment by spirillen** [comment]
don't forget https://github.com/mitchellkrogza/phishing/pull/286

**Comment by rsokolovs** [comment]
We know why, and that was mentioned by our colleague in https://github.com/mitchellkrogza/phishing/pull/286 
There was this redirect functionality which allowed anyone to create redirects to anywhere.
Now it's limited only for those links what university needs.

**Comment by spirillen** [comment]
Super, thanks for the response. 

However I will make another MR to solve this before the weekend as your commit should be to the `falsepositive_regex.list` list

**Comment by spirillen** [comment]
Should be solved in 78772c9

**Comment by spirillen** [comment]
Should be solved in 78772c9

**Comment by rsokolovs** [comment]
Hi,
I see that we are removed from ALL-phishing-links.txt but we are still in ALL-phishing-domains.txt
Can you help?

**Comment by spirillen** [comment]
No that is a issue for @funilrys or @mitchellkrogza as I do not have access to their servers

**Comment by spirillen** [comment]
Is this still a issue?? or can we close the issue?

**Comment by rsokolovs** [comment]
It's resolved, thank you!

**Pull request closed without merging**
