### PR TITLE
Update add-domain to add lovemachina.com

### PR DESCRIPTION
**Pull request by g0d33p3rsec**
## Domain/URL/IP(s) where you have found the Phishing:

- https://lovemachina.com/MnI4dTllNHc2MzV4MEg=
- https://lovemachina.com/M1IyNTNhOHo2VjM5N28= 
- https://lovemachina.com/M3AxRjFZNDYzMjZSMkc= 
- https://lovemachina.com/M2wyeDRWNEQ1cTgzM3c=
- https://lovemachina.com/M1IyNDRyM1cyOTV5MHc=
- https://lovemachina.com/MzcyQjRSM1kzeDhoNHY= 
- https://lovemachina.com/M0oyUDRVMlMzVjJFOHo=
-  https://lovemachina.com/MzYyUzRJMEs3ZjNwM2Y= 

## Impersonated domain

- https://ww2.ukzn.ac.za/
- https://www.facebook.com/
- https://www.tiktok.com/
- https://betway.com

## Describe the issue

This site is currently serving a phishing kit.  The group was previously using onedailydealnow.com to host the kit.  Before that, they used cedarwoodhomes.com.au, vehicleutilityladder.com, tempoorestaurant.com, and mklogistics.com.pk.  All sites have screenshots available at urlscan.io.  

## Related external source

https://urlscan.io/result/218d4371-9ca0-4de0-a61b-cbcc8909f2b1/ 
https://urlscan.io/result/3c9d01b6-32d3-46ab-8c91-1488fb7dbdf5/
https://urlscan.io/result/de5eaca6-cb2d-4dd4-8932-61a0d227e4fc/ 
https://urlscan.io/result/e0c7a2c2-58c4-461d-aeb8-8e0d7a0b5374/ 
https://urlscan.io/result/8233467f-c0f6-41da-967d-87f504e03de8/
https://urlscan.io/result/dcc6ff23-af02-47eb-9b3b-089f99924d15/
https://urlscan.io/result/690eeae9-7657-4e9b-884f-3252d32837bf/ 
https://urlscan.io/result/a0bfd216-efcc-4712-9dad-75a95666b015/

### Screenshot

<details><summary>Click to expand</summary>

</details>

### CODE REVIEW

**Comment by g0d33p3rsec** [comment]
I would also appreciate any feedback on how to improve my reporting for future submissions.  I am usually able to follow the kit to its new domain within 24-48 hours following the take down of the previous host.  If I am following an activity group from site to site, is it preferred to report by domain, wildcard, or URI?  I am usually able to find the new domain in about a day, then it usually takes another day before I can start populating the endpoints after the search engines have re-indexed the related social media pages.

**Comment by spirillen** [comment]
Your use of the template looks fine

First box = Where the phishing reside
Second box = As you already do, The impersonated domain
Third box = Comment about the submission
Fourth box = IF == true; then have you found the domains somewhere else, then please add, to comply with any FOSS License
Fifth box = Screenshots of the phishing site are very appreciated, as other might not be able to see the site and therefor unable to confirm your commit. Would be nice if you could add this.

**Comment by g0d33p3rsec** [comment]
Excellent, thank you for the feedback.  I've added some screenshots to the PR.

**Comment by spirillen** [comment]
> Excellent, thank you for the feedback. I've added some screenshots to the PR.

I've moved one line to before the images... this makes them collapsed, take a look by clicking edit on the issue.

The edited version looks like this

```md
<details><summary>Click to expand</summary>

![image](https://github.com/mitchellkrogza/phishing/assets/108126637/be7ec62b-e86c-4a3b-9735-ee690b2fc63f)
![image](https://github.com/mitchellkrogza/phishing/assets/108126637/99244a1b-0632-4b57-9047-d90a8681dc1b)
![image](https://github.com/mitchellkrogza/phishing/assets/108126637/57f1cc0a-aec0-4e77-9bb7-570e119f3621)
![image](https://github.com/mitchellkrogza/phishing/assets/108126637/df8d2aa7-b820-4b74-b594-61f9b8d6cda6)

</details>
```

> If you feel a screenshot can say more than 1000 hard drives, do please feel free to add it here
> 
> **TIP**: Place your mouse on the line just above the `</details>` and paste your screenshot and make sure that there is at least one line spacing before and after the image code line. The tip will add" one line after the paste :wink:

-------

Now let me ask you, do you feel the issue template simple or do you have any suggestion for making it better(easier to understand)?

**Comment by spirillen** [comment]
PS: added back ticks... The issue is now 100% right. and provides all needed info + documentation.

A issue that can take no more than seconds to confirm or deny

**Comment by g0d33p3rsec** [comment]
Ah, thanks for the clarification.  The back ticks is the part that, for some reason, wasn't properly registering.  My mind being in "kill it with fire mode" likely didn't help, heh.

> Now let me ask you, do you feel the issue template simple or do you have any suggestion for making it better(easier to understand)?
Seeing the example, visually, works best for how my mind encodes things.  I have a fun mix of ADHD and ASD that sometimes requires me to see something from several perspectives before it clicks. 

I'm up to 30 or so endpoints on this current host.  Should I be updating anything here as I scan them into urlscan.io?  Also, if I get a response from one of the service providers and can confirm the malicious content has been taken down do I just open a separate PR to delete the domain or is there a different process?  This is host is taking a bit to respond to the abuse reports, often the content is taken down within a couple of days.

Thanks again for taking the time to ease the onboarding process.  I really appreciate it.

**Comment by spirillen** [comment]
> Seeing the example, visually, works best for how my mind encodes things. I have a fun mix of ADHD and ASD that sometimes requires me to see something from several perspectives before it clicks.

Happy to hear you can manage it, and thanks for sharing you wizz with us

> Should I be updating anything here as I scan them into urlscan.io?

Would be nice. Can I request you do mypdns.org to(my project) That would be the [issues](https://github.com/mypdns/matrix/issues/new?assignees=spirillen&labels=&projects=&template=domain_blacklist.yml) only.

Before you do, let me be sure you understand the file structure

### Add Phishing Domains

| File                                               | Contents                                                                                                                                                                                                                                                                                                                                      |
| -------------------------------------------------- |-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [add-domain](../main/add-domain)                   | This list are matching a records `1 to 1` or this domain only (hosts file style RFC:952 and RFC:953                                                                                                                                                                                                                                           |
| [add-wildcard-domain](../main/add-wildcard-domain) | This domain and all it's subdomains should be added. This means if an entire domain is being used for phishing i.e. `phishing.example.com`, then add it to the domain list (add-domain). If the phishing threat resides inside a subfolder of the domain i.e. `/sub/oath/phishing-script/payload.php` then add it to the url list (add-link). |

include the domain name only (no http / https) and no path (/something)

### Add Phishing Urls / Links

To add either a domain, subdomain or a number of URI's to the project, you should be understanding a bit about how it is working.

| File                         | Contents                    |
| ---------------------------- | --------------------------- |
| [add-link](../main/add-link) | this URI, and only this URI |

## Add phishing by IP

| File                                                           | Contents                                                                                    |
| -------------------------------------------------------------- |---------------------------------------------------------------------------------------------|
| [IP-addr.cidr.in-addr.arpa](../main/IP-addr.cidr.in-addr.arpa) | This is a list for blocking phishing by IP address in CIDR notated in-arpa style (rfc:5737) |
| [IP-addr.cidr.list](../main/IP-addr.cidr.list)                 | This is a list for blocking phishing by IP address in CIDR notation style (rfc:5737)        |
| [IP-addr.in-addr.arpa](../main/IP-addr.in-addr.arpa)           | This is a list for blocking phishing by IP address in in-arpa style (rfc:5737)              |
| [IP-addr.list](../main/IP-addr.list)                           | This is a list for blocking phishing by IP address in (strait forward) style (rfc:5737)     |

## False Positives

To be able to keep the whitelist as precise as possible, the Phishing DB are using 3 types of list.

| File                                               | Contents                                                                                                                                                                                                                                                                                                                                      |
| -------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| The [first list](../main/falsepositive.list)       | Matching `1 on 1`. This means, should we only whitelist IE. `subdomain1.example.com` but not `subdomain2.example.com`, then this is the list.                                                                                                                                                                                                 |
| The [other list](../main/falsepositive_regex.list) | (ALL) is [wildcard](https://github.com/Ultimate-Hosts-Blacklist/whitelist/blob/script/README.rst#all) based. This means every subdomains from `example.net` and lover level such as `subdomain1.example.net` & `subdomain2.example.net`. This list also accepts full regex. Except from ending `$` and `\\` as this is done by automatically. |
| The [third list](../main/falsepositive_rzd.list)   | (RZD) will probably never be used... Read the full doc here before attempting to making changes to it: https://github.com/Ultimate-Hosts-Blacklist/whitelist/blob/script/README.rst#rzd                                                                                                                                                       |

Do you have any questions regarding when or how to use the files for addition and deletion?

----------------

> Also, if I get a response from one of the service providers and can confirm the malicious content has been taken down do I just open a separate PR to delete the domain or is there a different process?

Yes please, 1 record = 1 Issue/MR, as it help keep things separated, when we have to look back in time to figure out what might have happened.

---------------

> Thanks again for taking the time to ease the onboarding process. I really appreciate it.

Your welcome... It will ease my work on @mitchellkrogza phishing as well :smiley: 

And again, there are no stupid question, so please just ask as it only can benefit both of us

**Comment by g0d33p3rsec** [comment]
I will probably need to look over the file structure a few times before I master it.  I had a chance to make 2 changes this morning that should help me get the feel of both sides of the workflow.  I deleted my initial MR because I accidentally committed the change to add the new link to the same branch I used to remove the previous host. #347 has the details of the previous host now returning 404's.  #348 has what should be the new host, which I track using a common indicator.  The search engines should have reindexed the social media that the group tends to use as watering holes by the time I get back from school this evening and I can start adding the new links as I find them.

Since I only have the single link so far but expect the list to grow with time, should I first update the single link to a domain entry here, after I have sufficient evidence, and then add additional links to the issue tracker you linked for your project?

**Comment by g0d33p3rsec** [comment]
I think the current host should be fine if I report the individual links but I will ultimately leave that up to the judgement of the maintainers.  From what I've observed from this activity group so far, the phishing kit seems to stay contained to a subdirectory of the primary domain.  I've attached a couple of screenshots below to offer you an idea of what I'm looking at.  The base64 string for the URL decodes to the target module to load the next stage, as I currently understand it. ```https://urlscan.io/responses/a7803be917cb7050e38514ad03138129c85f8b191e773f5de149e21d937faaf9/``` shows the contents of the response to the second request in the first screenshot.  Newfold Digital has been pretty good about responding to abuse reports, which leads me to feel that reporting the individual links is more appropriate at this stage.  It is an interesting ethical problem, trying to strike the golden mean between neutralizing the malicious content without causing unnecessary reputation damage to the host, who is most likely another victim.

Is there a better way to bring attention that the host has addressed the issue?  This group can move from host to host quickly and I would like to try to stay proactive with the housekeeping to avoid unnecessary false positives.

I've also attempted to add the links to your project.  I listed defanged URLs along with their related urlscan.io pages. [mypdns/matrix/#450](https://github.com/mypdns/matrix/issues/450) but wanted to double check to see if my approach was appropriate.
<details><summary>Click to expand</summary>

image
image

</details>

**Comment by spirillen** [comment]
> Newfold Digital has been pretty good about responding to abuse reports, which leads me to feel that reporting the individual links is more appropriate at this stage. It is an interesting ethical problem, trying to strike the golden mean between neutralizing the malicious content without causing unnecessary reputation damage to the host, who is most likely another victim.

:100: Nice, I like your thinking and your approach.

**Pull request merged**
