### PR TITLE
Add Forte Life

### PR DESCRIPTION
**Pull request by reinstej-sci**
Site used to phish cryptocurrency users/wallet holders by imitating www.forte.io.

### CODE REVIEW

**Comment by spirillen** [comment]
Is this only happening to me?? Or are you other unable to click anywhere as well?

image

**Comment by reinstej-sci** [comment]
This is normal based on how this phish is designed - the site will not
allow you to interact with it until you've connected a crypto wallet,
however once you do, it could be game over. Absolutely do not do this -
others have and have lost funds already.

**Comment by spirillen** [comment]
Hey @reinstej-sci Not that I don't believe you as it sounds very plausible and I'm about to hit the merge for you.

But do you have any links to other sources, articles etc that can back up your statement?

I'm asking cause I'm not able to setup a "learning" environment for this.

**Comment by reinstej-sci** [comment]
@spirillen - Please see our Twitter account (the legit one) at: https://twitter.com/FortePlatform. The pinned tweet "NFTs can contribute to a more..." has several replies from folks who have been scammed by that site. We also have direct emails from users as well. Our real site is www.forte.io, the phish site (a 1:1 copy) is www.fortes.life (jumping to /home is where the problem lies). A fake Forte twitter account was already taken down (https://twitter.com/FoundationForte) as well. Hope this helps.

**Comment by spirillen** [comment]
Another thing is, are you sure it is the right domain you have added as phishing?

*.life is correct encrypted

image


while *.io fails to validate it's certificate
image

Accessing `https://www.fortes.life/home` = 302

Accessing `https://www.forte.io/home` = DNS failure

image


Also if you are reviewing the page sources you'll notice that all `js` scripts are i plain extracted format on `forte.io` while they are called from there `*.js` scripts on `fortes.life`

image

From the search engines it looks like `forte.io` is the right domain to allow
image

While `fortes.life` is to be blocked, even from a domain level rather than just the url to a sub-page

image


## Conclusion

It looks like something is plain wrong here and it appears to me (in person) that things have been turned upside down, and then yet not.. :thinking: 

Do you have any thought on this one @mitchellkrogza , @funilrys ??

**Review by spirillen — CHANGES_REQUESTED** [review]
Move the domain to the domain lists according to the final conclusion of https://github.com/mitchellkrogza/phishing/pull/44#issuecomment-900098646

**Comment by spirillen** [comment]
image

pyfunceble -a --http -d fortes.life

    ██████╗ ██╗   ██╗███████╗██╗   ██╗███╗   ██╗ ██████╗███████╗██████╗ ██╗     ███████╗
    ██╔══██╗╚██╗ ██╔╝██╔════╝██║   ██║████╗  ██║██╔════╝██╔════╝██╔══██╗██║     ██╔════╝
    ██████╔╝ ╚████╔╝ █████╗  ██║   ██║██╔██╗ ██║██║     █████╗  ██████╔╝██║     █████╗
    ██╔═══╝   ╚██╔╝  ██╔══╝  ██║   ██║██║╚██╗██║██║     ██╔══╝  ██╔══██╗██║     ██╔══╝
    ██║        ██║   ██║     ╚██████╔╝██║ ╚████║╚██████╗███████╗██████╔╝███████╗███████╗
    ╚═╝        ╚═╝   ╚═╝      ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚══════╝╚═════╝ ╚══════╝╚══════╝
    
You are using the Beta version of PyFunceble 4.0.0!
Please take the time to communicate with us when you notice
something unusual.




Subject                                                                                              Status      Source     Expiration Date   HTTP Code  Checker      
---------------------------------------------------------------------------------------------------- ----------- ---------- ----------------- ---------- -------------
fortes.life                                                                                          ACTIVE      WHOIS      24-jul-2022       Unknown    AVAILABILITY

**Pull request closed without merging**
