### PR TITLE
Removing baky.com.br

### PR DESCRIPTION
**Pull request by gersonfs**
## Phishing Domain/URL/IP(s):

`baky.com.br`

## Impersonated domain

`baky.com.br`

## Describe the issue

Malicious files were created on this domain due to the use of an outdated version of laravel. We removed the files and did a general update of the site.

### Screenshot

<details><summary>Click to expand</summary>

</details>

### CODE REVIEW

**Comment by spirillen** [comment]
I don't see the problem. Closing 

image

dsearch baky.com.br

## Search result from External Hosts-Sources
@mypdns's External Hosts-Sources can be found [here](https://github.com/external-sources/hosts-sources?tab=readme-ov-file#external-sources)

```css
```

#### Sorted result

```css
```

### Search result from easylist

```css
```

## Search in [Matrix](https://mypdns.org/)


Search results from [Matrix](https://mypdns.org) blacklist project

```css
```


Did not find any matching RPZ records


+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
\+ Thanks to [My Privacy DNS](https://mypdns.org/) for this knowledge
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


Drilling for baky.com.br

baky.com.br.    3600    IN      NS      ns2.onehost.com.br.
baky.com.br.    3600    IN      NS      ns1.onehost.com.br.
baky.com.br.    14400   IN      A       189.113.6.130

**Comment by spirillen** [comment]
in response to https://github.com/mitchellkrogza/Phishing.Database/issues/897

In which lists do you see the domain??

**Comment by spirillen** [comment]
Ok, I have found your domain now in the https://raw.githubusercontent.com/mitchellkrogza/Phishing.Database/master/ALL-phishing-links.txt which seems NOT to be synced properly with https://raw.githubusercontent.com/mitchellkrogza/Phishing.Database/master/ALL-phishing-domains.txt

I have added it to my import tool, then we will have to see if it can handle URI's

**Comment by spirillen** [comment]
Can you please rebase your fork.

And keep in mind, there is no guaranties it will remove the domain from Phishing.Database, please see https://github.com/mitchellkrogza/phishing/issues/395

**Comment by gersonfs** [comment]
@spirillen rebase done

**Pull request merged**
