### PR TITLE
Update add-domain `mp8.pire.cc`

### PR DESCRIPTION
**Pull request by WebworkrNet**
## Domain/URL/IP(s) where you have found the Phishing:

Email spam

## Impersonated domain

I can't give any information on this. 
For security reasons I did not call up the link.

## Related external source

Virustotal:
https://www.virustotal.com/gui/url/def9066f4dcdb3d36456d7f701cf5c5bf47d88ee373ecec89b45bb25f9b0705a?nocache=1

## Describe the issue

- Malicious
- Malware
- Phishing
- Spam

Compare Virustotal.

### Screenshot

Virustotal:

Screenshot_20230817_205910_Firefox Nightly
<details><summary>Click to expand</summary>

</details>

### CODE REVIEW

**Comment by WebworkrNet** [comment]
Screenshot_20230817_210235_FairEmail
Screenshot_20230817_210244_FairEmail

**Comment by spirillen** [comment]
redirect to duckduckgo for me

**Comment by spirillen** [comment]
on a diff virt install I'm redirected to `fnpnews.moneyextreme.co.in/FR/63465cr/?bet=28368923`

**Comment by spirillen** [comment]
Requested a test https://matrix.rocks/notice/AYpcbZ6HIlxLEUraTo

**Comment by spirillen** [comment]
This was also tested by [iam-py-test](https://matrix.rocks/users/AYVG88iqEoyKhDB2K8) in https://matrix.rocks/notice/AYpcbZ6HIlxLEUraTo and he got redirected to yahoo, Can't confirm other than it is redirecting

**Comment by WebworkrNet** [comment]
It may be that the target domain `moneyextreme.co.in` have been classified as harmful and therefore against harmless (DuckDuckGo, Yahoo!) redirects from an administrator or Providers have been exchanged?

I can only speculate there.

First of all, no admission to the locklist?

**Comment by spirillen** [comment]
Now the url in OP redirects me to a page with Google spyware... So is it possible you can copy/paste the full url again... and rebase this MR?

image

<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 | google-analytics_analytics.js | << | `www.virustotal.com` | 3 | get | script | `https://www.google-analytics.com/analytics.js` |
| +2 | \|\|google-analytics.com/analytics.js$script,redirect-rule=google-analytics_analytics.js:5 | -- | `www.virustotal.com` | 3 | get | script | `https://www.google-analytics.com/analytics.js` |
| +2 | \|\|google-analytics.com^ | -- | `www.virustotal.com` | 3 | get | script | `https://www.google-analytics.com/analytics.js` |
| +2 | \|\|googleapis.com^ | -- | `www.virustotal.com` | 3 | get | css | `https://fonts.googleapis.com/css2?family=Google+Sans:wght@400;500;600;700&display=swap` |
| +2 | \|\|recaptcha.net^ | -- | `www.virustotal.com` | 3 | get | script | `https://recaptcha.net/recaptcha/api.js?render=explicit` |
| +1 | \|\|gstatic.com^ | -- | `www.virustotal.com` | 3 | get | script | `https://www.gstatic.com/dialogflow-console/fast/df-messenger/prod/v1/df-messenger.js` |
| +1 | \|\|recaptcha.net^ | -- | `www.virustotal.com` | 3 | get | script | `https://www.recaptcha.net/recaptcha/api.js?render=explicit` |
| +1 | googletagmanager_gtm.js | << | `www.virustotal.com` | 3 | get | script | `https://www.googletagmanager.com/gtm.js?id=GTM-KFBGZNL` |
| +1 | \|\|googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager_gtm.js:5 | -- | `www.virustotal.com` | 3 | get | script | `https://www.googletagmanager.com/gtm.js?id=GTM-KFBGZNL` |
| +1 | \|\|googletagmanager.com^ | -- | `www.virustotal.com` | 3 | get | script | `https://www.googletagmanager.com/gtm.js?id=GTM-KFBGZNL` |
| +1 | \|\|gstatic.com^ | -- | `www.virustotal.com` | 3 | get | script | `https://www.gstatic.com/dialogflow-console/fast/df-messenger/prod/v1/df-messenger.js` |
| +1 | \|\|recaptcha.net^ | -- | `www.virustotal.com` | 3 | get | script | `https://www.recaptcha.net/recaptcha/api.js?render=explicit` |
| +1 |  |  | behind-the-scene | 0,3 | get | xhr | `https://[ff00::]/nscl/moz-extension://5db5a3ff-a6af-450c-a6d8-809e451483a5/syncMessage?id=4b2633d5aa.bae%2Chttps%3A%2F%2Fwww.virustotal.com%2Fgui%2Furl%2Fdef9066f4dcdb3d36456d7f701cf5c5bf47d88ee373ecec89b45bb25f9b0705a%3Fnocache%3D1&url=https%3A%2F%2Fwww.virustotal.com%2Fgui%2Furl%2Fdef9066f4dcdb3d36456d7f701cf5c5bf47d88ee373ecec89b45bb25f9b0705a%3Fnocache%3D1&top=true&msg=%7B%22id%22%3A%22fetchChildPolicy%22%2C%22url%22%3A%22https%3A%2F%2Fwww.virustotal.com%2Fgui%2Furl%2Fdef9066f4dcdb3d36456d7f701cf5c5bf47d88ee373ecec89b45bb25f9b0705a%3Fnocache%3D1%22%7D` |
</details>

**Comment by iam-py-test** [comment]
The URL from VT is `http://mp8.pire.cc/34546de4235m342356?affsub2=qwB0&st=8/17/2023+8:03:06+AM`

**Comment by spirillen** [comment]
Thanks @iam-py-test 

This domain and url are as dead as I can find them, closing

**Pull request closed without merging**
