### PR TITLE
Update IP-addr.cidr.list

### PR DESCRIPTION
**Pull request by whisbear**
## Related external source
#84
#85
#86
#87

### Screenshot
<details><summary>Click to expand</summary>
</details>

### CODE REVIEW

**Review by spirillen — CHANGES_REQUESTED** [review]
You are missing the CIDR notation.... 

If this is a submission for the particular IP addresses, you "just" add the `/32` to the end of the IP as in the example line

https://github.com/mitchellkrogza/phishing/blob/828ba2c7cf74c42ec3d875b9049598191d3d4c8d/IP-addr.cidr.list#L2

**Comment by spirillen** [comment]
I though you where in doubt.

Tell me if it is **_ONLY_** the IP `52.229.21.156` as listed you want to block **_OR_** it is 255 IP addresses.

In this case from `52.229.21.0' to `52.229.21.255`

**Comment by spirillen** [comment]
Found this table you can start out on, then I think I will make a "smaller" one which will be easier to look at conpared to this repo

`https://kb.wisc.edu/ns/page.php?id=3493`

**Comment by whisbear** [comment]
> I have now made this table of SubMask / CIDR conversion, Is it useful or do you have questions to it.

useful

**Review by spirillen — APPROVED** [review]

**Pull request merged**
