### PR TITLE
Add phishing sites

### PR DESCRIPTION
**Pull request by Zachinquarantine**

### CODE REVIEW

**Review by spirillen — CHANGES_REQUESTED** [review]
You should move `jobsamericanairline.com` to the domain list (https://mypdns.org/my-privacy-dns/matrix/-/issues/1885) as only `aa.com`is used by American Airlines for public affairs

You should actually do the same for `restore637908-coinbase-us.web.app`  no reason to only submit a link to a subpage, the entire domain is used for scam

**Comment by Zachinquarantine** [comment]
> 
> 
> You should move `jobsamericanairline.com` to the domain list ([mypdns.org/my-privacy-dns/matrix/-/issues/1885](https://mypdns.org/my-privacy-dns/matrix/-/issues/1885)) as only `aa.com`is used by American Airlines for public affairs
> 
> You should actually do the same for `restore637908-coinbase-us.web.app` no reason to only submit a link to a subpage, the entire domain is used for scam

done

**Review by funilrys — CHANGES_REQUESTED** [review]
Can you please add `systemww.trackinglink.top` into the `add-domain` file, please. 

Thank you!

**Comment by spirillen** [comment]
> Can you please add `systemww.trackinglink.top` into the `add-domain` file, please.
> 
> Thank you!

This is one of the reason I go for one domain = 1 issue :wink:

**Comment by Zachinquarantine** [comment]
> 
> 
> Can you please add `systemww.trackinglink.top` into the `add-domain` file, please.
> 
> Thank you!

then what's the add-url file for? hacked domain promoting scams?

**Comment by spirillen** [comment]
> > Can you please add `systemww.trackinglink.top` into the `add-domain` file, please.
> > Thank you!
> 
> then what's the add-url file for? hacked domain promoting scams?

Yep, small simple, but yet explaining note.

I don't have to be an essay, but enough for everyone to get them self a quick image of why... also in two years when they find this issue from a search of **why** is thisdomain record blacklisted

**Pull request merged**
