### PR TITLE
Update add-link

### PR DESCRIPTION
**Pull request by hellyeahs**

### CODE REVIEW

**Comment by hellyeahs** [comment]
Hey spirillen, will you come back to IRC?

**Comment by hellyeahs** [comment]
Well, I guess you don't mind if I ask here. Where are the domains or urls added here reported? malicious domains are still in active use and I wonder what effect it will have on them

**Comment by spirillen** [comment]
Before I answer, let me point a few Q towards you on this particular questions of yours. (Because I'm curious :smiley: )

1. How did you find this repository?
2. What are your expectations for the commits you are providing?
3. What do you and did you think would happen to your work in this repo

**Comment by hellyeahs** [comment]
> Before I answer, let me point a few Q towards you on this particular questions of yours. (Because I'm curious  )
> 
> 1. How did you find this repository?
> 2. What are your expectations for the commits you are providing?
> 3. What do you and did you think would happen to your work in this repo

I found this repo while searching for keys on github.

**Comment by spirillen** [comment]
ok, 

This repository is primarily for contributing to https://github.com/mitchellkrogza/Phishing.Database :wink: and that is used in by virustotal. So your contributions rach rather fare by small work 

> Please do not make any Pull Requests here
> Only send PR's on https://github.com/mitchellkrogza/phishing
>
> This is only for additions, removals will remain handled here through issues and whitelisting.
> Source: https://github.com/mitchellkrogza/Phishing.Database/issues/215

This said, everybody are free to use these data as they sees fit for them.

**Comment by hellyeahs** [comment]
> This said, everybody are free to use these data as they sees fit for them.
> 
> >

cool. Thanks for information

**Pull request merged**
