### PR TITLE
Add iwan2travel.com to add-wildcard-domain

### PR DESCRIPTION
**Pull request by g0d33p3rsec**
## Domain/URL/IP(s) where you have found the Phishing:

```
https://iwan2travel.com/M0MxSjduODQxeDh4OTc=
https://iwan2travel.com/M3gyaDhLMkc3ZDluOEU=
https://iwan2travel.com/M2wybzhxMjg1TThROXo= 
https://iwan2travel.com/M0cxSDNiMm0wazJiMUs=
https://iwan2travel.com/MmwyWDlpNVk5dzFLMEU=
https://iwan2travel.com/MXY2WTE5ODUyUTVNMDQ=
https://iwan2travel.com/M0EyYTZyMkYzazJWNHk=
https://iwan2travel.com/M3owdjdpM1kxaThnNmE=
https://iwan2travel.com/M2QyazU0Nk0wODE0Nkg=
https://iwan2travel.com/M1oyWDRWMkk4QTJTMjE=
https://iwan2travel.com/MzAyRDhyM0MwdjAxNXk=
https://iwan2travel.com/M3oyRzFvMHY1NDEyM0M=
https://iwan2travel.com/M28xcDk3OUI2MzBGMUg=
https://iwan2travel.com/M3kyWjhhME44ZTFlMTI=
https://iwan2travel.com/M24ydDgwM1UyYzdBNDk=
https://iwan2travel.com/M1YyTzRYMlk2RzJwMmo=
https://iwan2travel.com/M3kyNzhWMmkwRjZDN2E=
```

## Impersonated domain

```
https://facebook.com/
https://www.instagram.com/
https://www.betway.co.za
https://ff.garena.com
https://ww1.ukzn.ac.za/
```

## Describe the issue

This site is now hosting the kit that was previously at applesforfred[.]com(#369),  theaerie[.]ca (#367) , nico[.]sa (#366), and ajstelecom[.]com[.]mx (#362)

## Related external source

```
https://urlscan.io/result/5fac7988-c559-4b51-bca3-c00ecfa5c843/
https://radar.cloudflare.com/scan/482cdb8e-6aea-492d-a2af-d4b41c39c722/
https://radar.cloudflare.com/scan/c0f533bd-0a95-41d4-934d-ddd6a693f48f/
https://radar.cloudflare.com/scan/c2154606-6eb6-46a9-bac9-086ff70adcb1/
https://urlscan.io/result/c7fa2160-54b4-4776-b79d-e4bc799f7abc/
https://urlscan.io/result/86ff1031-bf54-4379-8d93-697c841d1230/
https://urlscan.io/result/e5b6dca7-8950-4985-a7f0-bd72be549367/
https://radar.cloudflare.com/scan/1c693b23-8b3d-4dbb-8800-4af34eca2960/
https://radar.cloudflare.com/scan/696df281-714f-4524-8f06-ef8732a0b504/
https://urlscan.io/result/f8443413-c7bc-46da-998e-fb626eb8a3c4/
https://radar.cloudflare.com/scan/9e48c4fd-3410-4a43-9ede-4b2ba18802e1/
https://radar.cloudflare.com/scan/f7569e83-01cc-4e9c-8560-b98fd8ab54fe/
https://radar.cloudflare.com/scan/180eaf85-5dc0-4a51-b380-c81e5a8a7eb3/
https://radar.cloudflare.com/scan/b690ca5b-929c-495d-a7b1-ac7cf1f5757a/
https://radar.cloudflare.com/scan/1859aa37-c48d-49a6-a774-50f277d00e24/
https://radar.cloudflare.com/scan/b50e4e9c-6fec-4580-bf82-6e603202dcc3/
https://radar.cloudflare.com/scan/61579873-e6b4-46ea-81aa-3fc75f83ca0a/
```

### Screenshot

<details><summary>Click to expand</summary>

image
image
image
screenshot
image
image
image
image
image
image
image
image
image

</details>

### CODE REVIEW

**Comment by spirillen** [comment]
Thanks again for your contribution

**Comment by g0d33p3rsec** [comment]
@spirillen just a heads up, since yesterday, I've noticed some apparent changes that are causing many of my scans to fail.  I suspect the threat actors are actively trying to prevent scans from the services listed in my previous reports.  I'm finding some work arounds but will need to adjust future reports, possibly omitting the links to many of the third-party sources, which tend to be the results of scans I initiate anyway instead of where I am finding the URIs.  Are you okay with me listing future domains primarily by malicious URI and supporting with screenshots or do you have any other suggestions for modifying the external sources my future reports (I should be able to still feed the sites into my Virus Total collection, but that doesn't offer easy access to screenshots)?

Here's what I've been getting from most attempted scans from urlscan.io
image
Compared to accessing the URI using a different method
image

**Comment by spirillen** [comment]
@g0d33p3rsec 

The field `External Sources` is primarily for when you pick up your knowledge from other open sources, to stay within the licenses, which always requires you to inform about your sources.

So as long as you using the external tools, like `urlscan.io` && `radar.cloudflare.com` (which personally is blacklisted for phishing, malicious, tracking etc.) to scan the others, without required information about how you have obtained your knowledge, I'm all fine about **_not_** promoting trackers and spyware :smirk:

**Comment by g0d33p3rsec** [comment]
@spirillen awesome, thanks!

> So as long as you using the external tools, like `urlscan.io` && `radar.cloudflare.com` (which personally is blacklisted for phishing, malicious, tracking etc.) to scan the others, without required information about how you have obtained your knowledge, I'm all fine about **_not_** promoting trackers and spyware 😏

I get why you would view cloudfare as in a gray-zone but am less clear about why you see Recorded Future's product as semi-malicious.  I have similar issues with cloudfare and their way of MitM'ing much of the traffic that transits the web but am a bit of a fan of Recorded Future's products and their free offerings.  ```Urlscan.io``` and ```tria.ge``` are both a part of my regular workflow.  Are there concerns with urlscan that I am overlooking and should consider?  Currently, I see the site as a sort of InternetArchive for potentially malicious web content and the act of adding content related to this kit as one of many paths I try to use to draw attention from other researchers.  I'll admit, I often find myself a bit conflicted as I am, one hand, a dues paying member of the EFF and, on the other, increasingly see myself moving towards CTI and its related fields as a career.

**Comment by spirillen** [comment]
@g0d33p3rsec 

> `Urlscan.io` and `tria.ge` are both a part of my regular workflow. 

Not more than usual, we all (should) know by now, that when we can't find the price tag, it is because it is sitting on our bags....

My biggest concern here was in reference to cloudflare.

> I often find myself a bit conflicted as I am, one hand

Don't worry, you will find what feels right to you, once you found what you feels most confident with, and since you are (hopefully) better to C++ than me, this will soon be, as you are trying and testing in both universes.

> Currently, I see the site as a sort of InternetArchive

Well, you should be writing your own screen grabber, and let it run from foreign locations. You could take a peak at https://github.com/claffin/cloudproxy, that project is making a proxy=>proxy thing.

**Pull request merged**
