### PR TITLE
feat: add linkfire domains to false-positive list

### PR DESCRIPTION
**Pull request by FalconerTC**
Closes https://github.com/mitchellkrogza/Phishing.Database/issues/619

### CODE REVIEW

**Comment by spirillen** [comment]
What precaution have you taken to avoid spreading #phishing in the future?

<details><summary>note to self (@spirillen)</summary>

- `lnk.to`: https://0xacab.org/my-privacy-dns/matrix/-/issues/614567
- `lnkfi.re`: https://0xacab.org/my-privacy-dns/matrix/-/issues/649954
- `linkfire.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/18470

</details>

**Comment by FalconerTC** [comment]
Our app isn't a wide-open link shortener. It redirects users to a page listing streaming platforms for music/podcasts, and enables them to create a simple personal website with a WYSIWYG editor. User customization is text only, and we don't have any evidence of our app being used for phishing. Please let me know if I can answer any more questions about it.

**Comment by FalconerTC** [comment]
@spirillen Do you have time this week to take a look at this? We'd really like to get our domains off this list.

**Comment by spirillen** [comment]
> It redirects users to a page listing streaming platforms for music/podcasts

And collect users data by tracking for selling. You redirect traffic versus having users do right, and post the straight link so people know were they end and can take a proper deposition based on knowledge.

I have posted the urls to the issues concerning your domains, that is where My Privacy DNS supports these questions, not on random third party platforms.

Regarding weather these might have final destinations which is containing phishing sites is out of my hands to lookup, so until https://github.com/mitchellkrogza/Phishing.Database/issues/619 is answered or solved I can't do much here, as I do not have access to @mitchellkrogza log files

**Comment by spirillen** [comment]
closing as inactive

**Pull request closed without merging**
