### PR TITLE
add more phish

### PR DESCRIPTION
**Pull request by Zachinquarantine**

### CODE REVIEW

**Comment by Zachinquarantine** [comment]
^ the site added above is a clever paypal phish that only works when you access it through hxxps://www.linkedin[.]com/slink?code=dxmZhmK?Duarr=SupportRiyermcsxh

**Review by spirillen — CHANGES_REQUESTED** [review]
`http://tabitha-cambodia.org/ `(https://github.com/mitchellkrogza/phishing/pull/13/files#diff-845088edabaa78cbd18254b02cf325eb8e6d53877ff6dbdaaef1858a45282510R2) should no longer be need: See https://mypdns.org/my-privacy-dns/matrix/-/issues/1841#note_3439 (https://github.com/mitchellkrogza/phishing/pull/14, https://github.com/mitchellkrogza/phishing/pull/10, https://github.com/mitchellkrogza/phishing/pull/9,https://github.com/mitchellkrogza/phishing/pull/8)


The rest seems fine to me :smile: :wave: 

```
pyfunceble -a --database-type mariadb -d mfgxfjgfdgjhk.com managewebsapps-verfyinginformtions.mfgxfjgfdgjhk.com managewebsapps-verfyinginformtions.mfgxfjgfdgjhk.com postnoopakee.wpengine.com www.mdscbenin.org --dns 127.0.0.1:5302

Subject                                                                                              Status      Source     Expiration Date   HTTP Code  Checker      
---------------------------------------------------------------------------------------------------- ----------- ---------- ----------------- ---------- -------------
managewebsapps-verfyinginformtions.mfgxfjgfdgjhk.com                                                 ACTIVE      DNSLOOKUP  Unknown           Unknown    AVAILABILITY 
managewebsapps-verfyinginformtions.mfgxfjgfdgjhk.com                                                 ACTIVE      DNSLOOKUP  Unknown           Unknown    AVAILABILITY 
mfgxfjgfdgjhk.com                                                                                    ACTIVE      WHOIS      29-jun-2022       404        AVAILABILITY 
postnoopakee.wpengine.com                                                                            ACTIVE      DNSLOOKUP  Unknown           200        AVAILABILITY 
www.mdscbenin.org                                                                                    ACTIVE      DNSLOOKUP  Unknown           Unknown    AVAILABILITY
```


<details><summary>note to self (@spirillen)</summary>

<details><summary>Click to unfold</summary>

image


</details>



</details>

**Review by spirillen — APPROVED** [review]
I'll remove `tabitha-cambodia.org` in https://github.com/mitchellkrogza/phishing/pull/14

**Comment by spirillen** [comment]
That domain have been reactivated and the site hosts phishing again.

image


> Source: https://mypdns.org/my-privacy-dns/matrix/-/issues/1841#note_14851

**Pull request merged**
