### PR TITLE
Update add-domain

### PR DESCRIPTION
**Pull request by cecilita2912**
## Phishing Domain/URL/IP(s):
https://conecamp.onrender.com/

## Impersonated domain
`https://conecamp.onrender.com/`

## Describe the issue

this is a fraud page that spoofing a legitimate domain that is where i Work 
### Screenshot

<details><summary>Click to expand</summary>

image

</details>

### CODE REVIEW

**Comment by spirillen** [comment]
what is the Impersonated domain?

**Comment by cecilita2912** [comment]
Fraud Domain: https://conecamp.onrender.com/

Legitime Domain: https://pacinet.cp.com.pe/login

**Comment by spirillen** [comment]
I do see the suspicion in `https://pacinet.cp.com.pe/login` but not the similarity to `https://conecamp.onrender.com/`

image


PS: Please use back ticks to surround any links

**Comment by cecilita2912** [comment]
It seems the page has been modified

this is how it looked before
pacinet

**Comment by g0d33p3rsec** [comment]
> It seems the page has been modified
> 
> this is how it looked before pacinet

I am seeing artifacts of what you've reported on a VirusTotal scan from yesterday.
```https://www.virustotal.com/gui/file/907c30ce2f90d775fe16840bd64351e04d492c54cf867a7ee9116ce894d73674/behavior```
image

I also see the response that @spirillen observes when scanning the site with urlscan ```https://urlscan.io/result/1b2b1ab7-aa44-444f-abef-c630112bacb8/#summary```
image
 
There could be an intermediate traffic distribution system causing the inconsistent behavior.

**Comment by spirillen** [comment]
Closing as solved.

Please do reopen if you find new data

**Pull request closed without merging**
