### PR TITLE
Add malicious links discovered by exposed .ru tld

### PR DESCRIPTION
**Pull request by g0d33p3rsec**
## Phishing Domain/URL/IP(s):

```
https://itsssl.com/Zqcp9
https://itsssl.com/YroXL
https://chomatruider.firebaseapp.com/
https://jascruipler.web.app/
http://u.to/w2G7IA
http://srv214512.hoster-test.ru/info-uc-edu-ec-idp/
http://srv214176.hoster-test.ru/Correos23/correos/auth/index.php
http://srv214615.hoster-test.ru/uts-edu-co-idp/
http://srv214413.hoster-test.ru/arub/P22.html
```

## Describe the issue

While following up on a link related to `brunotasso.com.br` (#413) today, a broken redirect led me to `srv214734.hoster-test.ru`. While reviewing the screenshots for the IP address of that host on `urlscan.io`, I noticed many apparent lure login pages. Scanning the related URIs with VirusTotal confirmed each as malicious.

## Related external source

```
https://urlscan.io/ip/31.28.24.131
https://www.virustotal.com/gui/url/92a1ae56a0b9754df8286844fec28be3e1cd6f1e55572271ab9fc862710b5af0
https://www.virustotal.com/gui/url/2bb24f46f271959f533907bf7c0338ca70b5ae43cb4f0b0db1e4df5070bb8564
https://www.virustotal.com/gui/url/28ac836a0e4a4426c6fe2786521fe0927941a1317a0d11c40ffdc79d9da09d5e
https://urlscan.io/domain/srv214616.hoster-test.ru
```

### Screenshot

<details><summary>Click to expand</summary>

712c5e8a-77c4-472d-bb9c-dbf3b19f605e
2fb62c16-ee96-4336-aae6-449fc8fd9071
631c0884-9aa0-4225-a5f1-9c86554d599c
image

</details>

### CODE REVIEW

**Comment by spirillen** [comment]
The following list are coming from phishing army

```
srv154724.hoster-test.ru
srv160995.hoster-test.ru
srv173722.hoster-test.ru
srv183859.hoster-test.ru
srv184138.hoster-test.ru
srv184538.hoster-test.ru
srv185028.hoster-test.ru
srv187256.hoster-test.ru
srv187577.hoster-test.ru
srv187718.hoster-test.ru
srv187775.hoster-test.ru
srv187865.hoster-test.ru
srv189118.hoster-test.ru
srv189883.hoster-test.ru
srv190340.hoster-test.ru
srv190351.hoster-test.ru
srv190361.hoster-test.ru
srv190413.hoster-test.ru
srv190435.hoster-test.ru
srv190612.hoster-test.ru
srv190699.hoster-test.ru
srv191174.hoster-test.ru
srv191792.hoster-test.ru
srv191835.hoster-test.ru
srv191963.hoster-test.ru
srv196377.hoster-test.ru
srv202030.hoster-test.ru
srv205115.hoster-test.ru
srv205377.hoster-test.ru
srv207386.hoster-test.ru
srv207431.hoster-test.ru
srv207436.hoster-test.ru
srv207576.hoster-test.ru
srv208063.hoster-test.ru
srv211845.hoster-test.ru
srv212796.hoster-test.ru
srv213004.hoster-test.ru
srv213354.hoster-test.ru
srv213553.hoster-test.ru
srv213630.hoster-test.ru
srv213657.hoster-test.ru
srv213804.hoster-test.ru
srv213848.hoster-test.ru
srv213849.hoster-test.ru
srv213858.hoster-test.ru
srv213865.hoster-test.ru
srv213932.hoster-test.ru
srv213975.hoster-test.ru
srv214196.hoster-test.ru
srv214288.hoster-test.ru
srv214413.hoster-test.ru
srv214616.hoster-test.ru
srv214742.hoster-test.ru
```

**Comment by spirillen** [comment]
I'm missing some data regarding `hoster.ru`...

**Comment by spirillen** [comment]
How ever I do have this one in my RPZ zones :wink: 

```
16282018        *.ru.politics.mypdns.cloud      CNAME   .
```

**Comment by g0d33p3rsec** [comment]
> I'm missing some data regarding `hoster.ru`...
> 
> PS: I know they are related with `hoster-test.ru` but ruling them out without some reason, feels wrong in a phishing project 😄

I am okay with removing with that one until I have more evidence.  I was just casting a wide net to try to get control of that source until I had a chance to dig deeper.  I think the itsssl links may have also expired, I'll have to double check.

**Comment by g0d33p3rsec** [comment]
I've removed the unsupported domain and double checked the shortened links.  Feel free to suggest any further edits you feel I should consider.  I see this as a separate rabbit hole that could take some time to fully explore as I look over the list of subdomains you found though phishing army.  At the moment, I'm looking at this host as being some form of traffic distribution system, but I haven't had the opportunity for any sort of in-depth analysis.
image

**Review by g0d33p3rsec — COMMENTED** [review]
I've removed the weakly related domain until I can better support it's inclusion with additional evidence.

**Comment by spirillen** [comment]
All Russian hosting companies are rabbit holes as the Putin mafia boss  more or less controls them... and it have been that way for over 20 years... and if you don't do as your told... well, you better hope the fire department ain't controlled by the Boos.

**Comment by g0d33p3rsec** [comment]
> All Russian hosting companies are rabbit holes as the Putin mafia boss more or less controls them... and it have been that way for over 20 year

An unfortunate truth.  Also, the collaboration between the criminal and nation state threat actors.

**Pull request merged**
