### PR TITLE
Update add-domain

### PR DESCRIPTION
**Pull request by kalingaa**
## Phishing Domain/URL/IP(s):

`https://sampatnvlshwa.com/survey`

## Impersonated domain

`www.sampathvishwa.com`

## Describe the issue

`sampatnvlshwa.com` is a phishing domain link `sampatnvlshwa.com/survey` trying to impersonate the actual domain - samapth bank's internet banking portal

## Related external source

`https://sampath.lk`

### Screenshot
<!-- If you feel a screenshot can say more than 1000 hard drives, do please feel free to add it here

<details><summary>Click to expand</summary>

image

</details>

### CODE REVIEW

**Comment by kalingaa** [comment]
see attached

url https://sampatnvlshwa.com/survey where users are sent to via facebook
ads
the host redirect based on geo and some user agents

**Comment by kalingaa** [comment]
Screenshot 2024-10-29 at 00 30 43

**Comment by spirillen** [comment]
Tanks for your contribution.. merged

**Pull request merged**
