### PR TITLE
Malicious phishing OneUI 7 beta program link

### PR DESCRIPTION
**Pull request by IntelCorei5-8350u**
## Phishing Domain/URL/IP(s):

`https://samsungsecure.com/smartthingsfind.samsung.com/smart-switch`

## Impersonated domain

`https://developer.samsung.com/one-ui-beta`

## Describe the issue

When you click on this link on a Samsung mobile device (OneUI Android), you will risk your phone being locked - quite similar to iPhone lost mode.
This link is found in one of the many Facebook ads targeting Vietnamese users. I specifically found this link in one of the local Vietnamese forums discussing this issue
Depending on the browser it may redirect to the legitimate website. This only works as intended on Samsung devices.
## Related external source

https://voz.vn/t/qc-lua-%C4%91ao-lock-may-%C4%91oi-tien-chuoc-samsung.1039240/

### Screenshot

<details><summary>Click to expand</summary>

</details>

### CODE REVIEW

**Comment by spirillen** [comment]
Hi @IntelCorei5-8350u I understand why you would like to spread this domain to as many blacklists as possible, but I don't see why this should be phishing, for what I understand this is malicious software, not phishing.

Unless you can tell me where and how this is trying to extract data from the targeted user, I'm going to leave it at https://github.com/mypdns/matrix/issues/1380 | https://github.com/mypdns/matrix/commit/a63a5cdc95c9f75d04e058b6cdaecfbdb977a326 as malisious.

I can on the other hand recommend you and other to interact with [chongluadao](https://github.com/chongluadao) for the Vietnamese region.

**Comment by IntelCorei5-8350u** [comment]
> Hi @IntelCorei5-8350u I understand why you would like to spread this domain to as many blacklists as possible, but I don't see why this should be phishing, for what I understand this is malicious software, not phishing.
> 
> Unless you can tell me where and how this is trying to extract data from the targeted user, I'm going to leave it at [mypdns/matrix#1380](https://github.com/mypdns/matrix/issues/1380) | [mypdns/matrix@a63a5cd](https://github.com/mypdns/matrix/commit/a63a5cdc95c9f75d04e058b6cdaecfbdb977a326) as malisious.
> 
> I can on the other hand recommend you and other to interact with [chongluadao](https://github.com/chongluadao) for the Vietnamese region.

 I have to admit that there's not much information about this.
This is what I gathered myself after reading on various Samsung Galaxy Facebook groups + my own test (on a non-Samsung device)

The hyperlink saying to login into your Samsung account only works on a Samsung OneUI Android device with Samsung Internet browser (I would still want the website to be blocked for others' safety), where it would launch the "Samsung Members" app on the device and asked for a login with the already signed in Samsung account on the device (some people says it's the legitimate app by samsung preinstalled on the device, while others argue that it would redirect to a fake login page) where you may or may not input the password and press yes or agree to complete log in.

After a few days, the victim's phone will be locked with a password they have no access to. This locked screen is told to be triggered by going to the Samsung SmartThings Find website, with the Samsung Account associated with the device, choose the device, and press "Lock". They somehow have authorization to the victim's account, so I summitted the link here, with beliefs that they may have got the victim's account password. The bad actor then removes the locked device from the victims' Samsung Accounts, so they can't do anything with the device unless they factory reset the device (may or may not work).

The victims could still access their Samsung Accounts after their phone being compromised though, so at least the accounts are still safe. Their user data on their phone, lost forever.

You may close this if you find this submission inappropriate. Thanks for reading.

**Comment by spirillen** [comment]
Hi @IntelCorei5-8350u 

Thanks for the reply and more details, I do see the one potential phish here, but still leans more to malicious, as they are no request for ransoms, personal logging (Except the app popup) and then the phone are being removed from an (not required [PII](https://kb.mypdns.org/articles/MTX-A-79/PII) data collecting) Samsung Account of devices.

## Verdict

I'm going to add this because of:

Hopefully the only way, the people behind this annoyance can get the pin code, is by best, by using a browser page in full screen mode, making it appears to be the original app, or by running a key locker.

What I on the other hand tend to believe more my self: Samsung have been hacked once again...

**Comment by IntelCorei5-8350u** [comment]
> Hi @IntelCorei5-8350u 
> 
> Thanks for the reply and more details, I do see the one potential phish here, but still leans more to malicious, as they are no request for ransoms, personal logging (Except the app popup) and then the phone are being removed from an (not required [PII](https://kb.mypdns.org/articles/MTX-A-79/PII) data collecting) Samsung Account of devices.
> 
> ## Verdict
> 
> I'm going to add this because of:
> 
> Hopefully the only way, the people behind this annoyance can get the pin code, is by best, by using a browser page in full screen mode, making it appears to be the original app, or by running a key locker.
> 
> What I on the other hand tend to believe more my self: Samsung have been hacked once again...

Thank you so much!

**Pull request merged**
