### PR TITLE
See https://mypdns.org/my-privacy-dns/matrix/-/issues/1918

### PR DESCRIPTION
**Pull request by spirillen**
Suplememt to https://github.com/mitchellkrogza/phishing/pull/21 by https://mypdns.org/spirillen/phishing/-/tree/org-swap-claim.site

### CODE REVIEW

**Comment by mitchellkrogza** [comment]
Looks good to me

**Comment by spirillen** [comment]
> Looks good to me

It just strikes me... are your (@mitchellkrogza) phishing project capable of handling wildcarded domains?? Like the RPZ is? or are it more hosts only...?

**Comment by mitchellkrogza** [comment]
> > Looks good to me
> 
> It just strikes me... are your (@mitchellkrogza) phishing project capable of handling wildcarded domains?? Like the RPZ is? or are it more hosts only...?

I don't think so, I think that behaviour can only be provided through DNS and hosts. Depends how people ingest and use this data I guess.

**Comment by spirillen** [comment]
That is leaving this PR with two options... 

Link to https://mypdns.org/my-privacy-dns/matrix/-/blob/master/source/phishing/wildcard.list (true script or some other methodes)

OR

Close PR as unusable.

**Review by funilrys — APPROVED** [review]
LGTM!

**Comment by spirillen** [comment]
> LGTM!

@funilrys you noticed the comment about `Only usable if wildcard is supported` ?

**Pull request merged**
