### PR TITLE
Update add-link `https://a191bc.myshopify.com/…`

### PR DESCRIPTION
**Pull request by WebworkrNet**
## Domain/URL/IP(s) where you have found the Phishing:

Email spam

`https://a191bc.myshopify.com/_t/c/A1020004-177E2310540B3558-BCD6BC75?l=AADelM8UxEOuLVAVu5oa6Zmfxsfjusqe9IbnNCEQIqpQbCkHlWrY9tQ0L66%2BJLk0v%2BjYf4bNjHdJwV5tIhJefvhdbINwIw0GytEuaT4WH7NL2PkEJ6Ma1N%2BBTqjflx9NKnMcBbB%2Fz8yFpeePbxTTYD61Vnu6Zyx3yWy9ODRH8fEV58WGhPiiiEeSAhSPmE1lJBlUTUCAfGbx6J%2Bez1t1o8NVfoR%2FVORF2ACoY6bFotMQ1PLQqnsVSo72wIKBD9P1CWkSFldO4xdasT4tJNMhS2EPTuuCZf%2FnBFfr%2F44EIb%2BXwF2SRZEDBILRhdEbFbWLXoiEARIUwmTVt1E6f8QCFdj8ioi3a5X45LLd3fCFuHFHvGno1VKS5wYj826CTuu7EWavDXqKqjG06Y7u0B7tWIm2Ce54ouMb6%2FtLVC2s1HElu478CpG9yVes7OggZ5lrgHcxrOlS5yBg0oXLuJkCXYEIqwTC6k4M6O3HEJLWbCNEL%2BN%2FQOcILSAIQIAnHr0kwDsVCSpPefgSEgb68Xn2EayRLLeLvqZ%2BpW2uFufZ%2BVvFjVbiuPEuHzIHZXgddOHSEBiCLGNWIedW34W21KKErnS%2Fg6PpMo3MSRv0a7QBkvkjGWzCoEJ0f2H3eS1K9RbQnuRuOXCj20JKFSFC4%2BDHT4m3LMkRPE7%2BifxfJ89vD2yGpG8k7fbEUpsBeR%2BOjrLrMiEelY8oWMN3vB7wlTA%3D&c=AAB94XVIyfrmuBI%2B%2B0kFch5RWkfJB9YwW4cO7TikajdtwLc94puHbu6inItZ34sFrQKzkrTYHwVrFIuuU0q%2FWtKo1vYT7%2BwdaxL3VIX2cLibvhWqx8TCQj6ovmcGT1ICc6uZBbm0af5FvB5rKcqcqLsCGV%2FFTlgmeNKmbN%2BgQ2Adythfb3sAeumKW67ltdDpaNHYZJtSWxy%2Bt4y0hMChmXuLL6dksvq86V0H8IxpTjUfLPTjwgjQhRkVRMZ11ev1drlz5Enh%2FidFZRApvqPVRV4WUKVHxHnkgRO4%2Fj3vu%2FA0xQnNZcx6Y9rrphtWN86Qzl4SKYTKP1IRn%2FRveryCE%2FpWCaOJlZ5guVT1daz0VuTuXXSDmJjjsx26DVP7iie2nDhSoWz9m6XfVVadhUy9U9d7TZ6B8W98LsBu2eYazBXdEM5Sn%2BM%3D`

## Impersonated domain

Unknown, for security reasons I did not call up the link myself.

In addition, my email client is very restrictive (safe message view (styling, scripting and unsafe HTML removed)). The e-mail only contains an image with a hyperlink. I couldn't get any more keys from it. A further forensic examination is not possible for me due to the lack of an appropriate environment.

## Related external source

https://www.virustotal.com/gui/url/91a4f150809285a479100a36260c1f9e20d7a7b81473eee635f3d78d925fd171?nocache=1

## Describe the issue

Source code
```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w=
3.org/TR/REC-html40/loose.dtd"><html><head></head><body>
<div dir=3D"auto">
<div dir=3D"auto">
<div>
<figure>
<table border=3D"0" width=3D"100%" cellspacing=3D"0" cellpadding=3D"0">
<tbody>
<tr>
<td align=3D"left" width=3D"549"><a href=3D"https://a191bc.myshopify.com/_t=
/c/A1020004-177E2310540B3558-BCD6BC75?l=3DAADelM8UxEOuLVAVu5oa6Zmfxsfjusqe9=
IbnNCEQIqpQbCkHlWrY9tQ0L66%2BJLk0v%2BjYf4bNjHdJwV5tIhJefvhdbINwIw0GytEuaT4W=
H7NL2PkEJ6Ma1N%2BBTqjflx9NKnMcBbB%2Fz8yFpeePbxTTYD61Vnu6Zyx3yWy9ODRH8fEV58W=
GhPiiiEeSAhSPmE1lJBlUTUCAfGbx6J%2Bez1t1o8NVfoR%2FVORF2ACoY6bFotMQ1PLQqnsVSo=
72wIKBD9P1CWkSFldO4xdasT4tJNMhS2EPTuuCZf%2FnBFfr%2F44EIb%2BXwF2SRZEDBILRhdE=
bFbWLXoiEARIUwmTVt1E6f8QCFdj8ioi3a5X45LLd3fCFuHFHvGno1VKS5wYj826CTuu7EWavDX=
qKqjG06Y7u0B7tWIm2Ce54ouMb6%2FtLVC2s1HElu478CpG9yVes7OggZ5lrgHcxrOlS5yBg0oX=
LuJkCXYEIqwTC6k4M6O3HEJLWbCNEL%2BN%2FQOcILSAIQIAnHr0kwDsVCSpPefgSEgb68Xn2Ea=
yRLLeLvqZ%2BpW2uFufZ%2BVvFjVbiuPEuHzIHZXgddOHSEBiCLGNWIedW34W21KKErnS%2Fg6P=
pMo3MSRv0a7QBkvkjGWzCoEJ0f2H3eS1K9RbQnuRuOXCj20JKFSFC4%2BDHT4m3LMkRPE7%2Bif=
xfJ89vD2yGpG8k7fbEUpsBeR%2BOjrLrMiEelY8oWMN3vB7wlTA%3D&amp;c=3DAAB94XVIyfrm=
uBI%2B%2B0kFch5RWkfJB9YwW4cO7TikajdtwLc94puHbu6inItZ34sFrQKzkrTYHwVrFIuuU0q=
%2FWtKo1vYT7%2BwdaxL3VIX2cLibvhWqx8TCQj6ovmcGT1ICc6uZBbm0af5FvB5rKcqcqLsCGV=
%2FFTlgmeNKmbN%2BgQ2Adythfb3sAeumKW67ltdDpaNHYZJtSWxy%2Bt4y0hMChmXuLL6dksvq=
86V0H8IxpTjUfLPTjwgjQhRkVRMZ11ev1drlz5Enh%2FidFZRApvqPVRV4WUKVHxHnkgRO4%2Fj=
3vu%2FA0xQnNZcx6Y9rrphtWN86Qzl4SKYTKP1IRn%2FRveryCE%2FpWCaOJlZ5guVT1daz0VuT=
uXXSDmJjjsx26DVP7iie2nDhSoWz9m6XfVVadhUy9U9d7TZ6B8W98LsBu2eYazBXdEM5Sn%2BM%=
3D" target=3D"_blank" rel=3D"nofollow ugc noopener" data-saferedirecturl=3D=
"https://www.google.com/url?q=3Dhttps://email.mg-d0.substack.com/c/eJxUkcGO=
nTAMRb-G7AY5TkJgkUW7eL-BnNi8lxYIIkHT-fuKaaV2Fl4d2fdYN1GTZzk_wnKKvL3LmsomisN=
gaHGsJOhhwhG99l7JRnmdn7LLSU14pvaPDoioXkGMgI-LieyMaC8sE1gNTkcNaWKrckBAAyMa1H=
bQrjf9tEStTXLg3WIn8P2PPaZ3Gl6dhe35xtDXK9ZG6WefyqZynW_X2yW08xK1hldrR-3Mtw4fH=
T7qRvUlnFY67oUOH_DfjMxgp0iU3CJsjV8m9sboaOOonfEdPrQ6rjinsm3XntvHLDvFVfhP2nHF=
NSdquexz5qBHHHEAdQbiGsuvvpb1umGH38_SqJUz16Oz8LyFPx-oV-SyUd7DXlpe_h6rNx-1Ve1=
rFVeV8zNocACjdeZ3AAAA__9B4Iti&amp;source=3Dgmail&amp;ust=3D1692913588418000=
&amp;usg=3DAOvVaw0tqBGHZdjfwAZ9e7waAgF2"><img class=3D"CToWUd" style=3D"dis=
play: block; margin-left: auto; margin-right: auto;" src=3D"https://ci6.goo=
gleusercontent.com/proxy/BonbLIVzsAH40kpx0ThCHBajChlJtB5auW5g5tqHfMZobJo-rD=
uBcCJ0XkiZgYS2oDXyj5zUG2RPMCFPw_6V9aMTL34TJTfZuASz7HCNAF2akj6k9sNVKbzanOw6Q=
M4BrNwnlRSvdsLrQjosHB_cKg9ImsR1v3wJzguyIrHqC3RFL7MIGCvNauMoo_eo241J71VlMTQD=
LFOVohRFQs8Bt5846ryIpTirSb2Z75YBYZ-AV3uFaOaxgzvEoCFbaFerZGfK93I9oaqS8wW7vpF=
u6FJE5rUQ6eIakZ9R-D_FJeHniSltvg=3Ds0-d-e1-ft#https://substackcdn.com/image/=
fetch/w_549,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fs=
ubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F920888fa-6bfd-4640-=
8ab2-97ad6507900e_549x713.png" alt=3D"" width=3D"549" height=3D"713" data-b=
it=3D"iit"/></a></td>
<td>=A0</td>
</tr>
</tbody>
</table>
</figure>
</div>
<p>=A0</p>
</div>
</div>
<div>=A0</div>

</body></html>
```

### Screenshot

Screenshot_20230824_063755_Firefox Nightly
<details><summary>Click to expand</summary>

</details>

### CODE REVIEW

**Comment by spirillen** [comment]
Despite how much I hate this domain and it master `https://www.shopify.com/` for all their privacy invasion, then I bet it is better to try to contact them first.  If this in unsuccessful within 12 hours, then I reopen this issue.

**Comment by WebworkrNet** [comment]
I submitted the spam to [Spamcop.net](http:://www.spamcop.net) in parallel. The report has been sent to `abuse@shopify.com`. In the rarest of cases, I get a response from Spamcop from the recipients of the reports, and not in this case either.

And now?

**Comment by spirillen** [comment]
> And now?

We better reopen and add them to our lists

**Comment by WebworkrNet** [comment]
Thank you for merging

**Pull request merged**
