### PR TITLE
Update sites

### PR DESCRIPTION
**Pull request by Zachinquarantine**

### CODE REVIEW

**Review by spirillen — CHANGES_REQUESTED** [review]
Why did you re-add `versusbattle.net` I don't see why this should be on a phishing list.

Can you add a few words for why this should be added.

`Import-External-Sources/hosts-sources$ git grep 'versusbattle.net'` gives no hits.

**Comment by Zachinquarantine** [comment]
> 
> 
> Why did you re-add `versusbattle.net` I don't see why this should be on a phishing list.
> 
> Can you add a few words for why this should be added.
> 
> `Import-External-Sources/hosts-sources$ git grep 'versusbattle.net'` gives no hits.

... I never removed it, it was a steam phishing site but now it seems to 404.
https://scammer.info/t/vote-for-my-cs-go-team-scam/75870

**Comment by spirillen** [comment]
:rofl: 

`https://scammer.info/t/vote-for-my-cs-go-team-scam/75870` 403 access denied :smile: 

```hmtl
<title>Access denied | scammer.info used Cloudflare to restrict access</title>
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" type="text/css" media="screen,projection" />
<script async src='/cdn-cgi/bm/cv/669835187/api.js'></script></head>
```

**Comment by spirillen** [comment]
unfortunately it's still active...

versusbattle.net

**Review by Zachinquarantine — COMMENTED** [review]
another fake steam login page added (winskull[.]com)

**Pull request merged**
