### PR TITLE
myhermes-sendungs.com

### PR DESCRIPTION
**Pull request by technikamateur**
## Phishing Domain/URL/IP(s):
`https://Myhermes-Sendungs.com`

## Impersonated domain
`https://www.myhermes.de/`

## Describe the issue

This page tries to geht your personal data and says that you need to pay money in order to get "your parcel".

### Screenshot

<details><summary>Click to expand</summary>

</details>

### CODE REVIEW

**Comment by g0d33p3rsec** [comment]
I'm currently getting a 404 from the link you reported, do you have any other URIs from that domain?
```https://urlscan.io/result/aea62ea0-3bdb-4eb5-ade7-dfca444678f4/```
image

**Comment by spirillen** [comment]
Get 404 as well, closing as solved

**Comment by technikamateur** [comment]
Hi, I got another phishing SMS today, with the same URL. I am using a recursive DNS and it is still resoleveable. Urlscan can resolve it too.
Screenshot_20240505-110130_Firefox

**Comment by g0d33p3rsec** [comment]
> Urlscan can resolve it too.

URLScan returns a 404.  These screenshots are from the scan you linked.  VirusTotal shows the site as malicious but the last scan was 15 days ago.  There is a scan on urlscan from the same date, but it includes no results.  Does the URL include an endpoint other than that which you scanned?  I attempted to find other URIs via a search engine but I'm not seeing anything.  I don't doubt that you've received a lure, I'm just unable to confirm the malicious content.  This does look like a ruse similar to the USPS/ FedEx/ UPS delivery scams that we see here in the US.  If you're still receiving smishing messages, you can forward them to 7726 (Spam).
image
image
image
image

**Comment by technikamateur** [comment]
Thanks for your reply @g0d33p3rsec. I can still visit the site. Screenshot attached. I tried to access it with a VPN to USA and I get 404. Seems to be based on your location...

grafik

**Comment by g0d33p3rsec** [comment]
> I tried to access it with a VPN to USA and I get 404. Seems to be based on your location or browser language

Thank you for the additional information.  URLScan allows you to specify the source of the scan as well as the user-agent and referrer headers.  I'll try adjusting some of the parameters to see if I can confirm the behavior that you are seeing.
image

**Comment by g0d33p3rsec** [comment]
I'm still unable to reproduce your results but don't doubt that you are seeing the reported behavior.  On urlscan, if you click the options button before initiating the scan you can adjust the related parameters.  @technikamateur if you can try setting the scan so that it matches the headers you are sending to obtain your reported results you may have better luck than I.  I suspect the site may be using a traffic distribution system and geofencing to avoid inspection by researchers.

**Comment by spirillen** [comment]
Hi guys

@technikamateur, is it possible for you to share a screen dump of the mail(s) you have received + the full source of it? That can help us verify that the destination is remaining active and should be blocked.

And thanks for the screenshot you [posted](https://github.com/mitchellkrogza/phishing/pull/392#issuecomment-2094819074), would have witched you had added it to the original post.

**Comment by technikamateur** [comment]
I will also try to play around with urlscan. Thanks for your explanation! I hope, I will find some time this evening.

**Comment by g0d33p3rsec** [comment]
> I will also try to play around with urlscan. Thanks for your explanation! I hope, I will find some time this evening.

My pleasure.  I think it is an invaluable tool for this sort of thing.  Their dataset is also for pivoting through for finding related content.  Recorded Future also offers an automated [sandbox environment](https://tria.ge/) that allows free users many more options than their competitors.

Related to the sms screenshots, I do see related negative intelligence.
```https://twitter.com/tellows_de/status/1786655299593482533```
image
```https://www.tellows.de/num/017640154775```
image

**Comment by g0d33p3rsec** [comment]
> Is there also a way to report the abuse of phones numbers somewhere?

You can forward the message to 7726 (SPAM) which should trigger an investigation from your provider.
```
https://www.ofcom.org.uk/phones-telecoms-and-internet/advice-for-consumers/scams/7726-reporting-scam-texts-and-calls
https://consumer.ftc.gov/articles/how-recognize-and-report-spam-text-messages
https://www.getcybersafe.gc.ca/en/blogs/reporting-spam-text-messages-7726
```

**Comment by technikamateur** [comment]
I'm not able to fake everything with urlscan so that it works. I also tried to access the web page with my vserver in Frankfurt: Also 404. I think the webpage allows only IP's from Telekom and Vodafone (our local internet companies for private users), so it will be impossible for you to reproduce.

If you try to access a directory e.g. `https://myhermes-sendungs.com/css/` You'll get a 403 (forbidden). Interesting.

I created a full dump of the webpage in case you want to have a look...[Hermes Paketversand.tar.gz](https://github.com/mitchellkrogza/phishing/files/15224967/Hermes.Paketversand.tar.gz)

Aren't my SMS + wepage screenshots + the comments on  `https
//www.tellows.de/num/017640154775` enough for an entry in your list?

Btw: 7726 does not exist in my country :(

**Comment by spirillen** [comment]
> Aren't my SMS + wepage screenshots + the comments on `https://www.tellows.de/num/017640154775` enough for an entry in your list?

Yes, they is, now that I can see them. I'm using tor for privacy, so it ain't all the time I get the images right, sometimes they are just all white.

Can I ask you to rebase the commit?

PS: interesting their are 2 and 1/4 germane in this thread...

**Comment by spirillen** [comment]
Thanks for your patience and commit. It's been a pleasure to work together with you both

**Comment by technikamateur** [comment]
> Thanks for your patience and commit. It's been a pleasure to work together with you both

Thanks to you two. I've learned a lot :)

**Pull request merged**
