### PR TITLE
Add widget.trustmary.com to falsepositive.list

### PR DESCRIPTION
**Pull request by kalliome**
**Domains or links**
`widget.trustmary.com`

**More Information**
How did you discover your web site or domain was listed here?

We had 2 of our other domains set to false positive couple of weeks ago (trustmary.com & form.trustmary.com). This domain is used to embed review widgets and surveys to our customer websites. 

**Have you requested removal from other sources?**
We are in process on removing our domain from following sources:
- `https://seclookup.com/`

**Additional context**
We are a review management startup and we have a survey editor in which users can create their own surveys. We faced users who created surveys where they asked email and password. We have removed those surveys and implemented tool to detect phishing in the future. 

:exclamation:

We understand being listed on a Phishing Database like this can be frustrating and embarrassing for many web site owners. The first step is to remain calm. The second step is to rest assured one of our maintainers will address your issue as soon as possible. Please make sure you have provided as much information as possible to help speed up the process.

**Send a Pull Request for faster removal**
Users who understand github and creating Pull Requests can assist us with faster removals by sending a PR to **mitchellkrogza/phishing** repository, on the falsepositive.list file
> https://github.com/mitchellkrogza/phishing/blob/main/falsepositive.list
Please include the same above information to help speed up the whitelisting process.

### CODE REVIEW

**Comment by kalliome** [comment]
We got https://seclookup.com/ resolved, so pihishing datase is now only one where this domain is

**Comment by beeblebrx** [comment]
@spirillen I'm with @kalliome  and I can try to help you. What do you mean by "blocking privacy oriented connections"? Are you referring to Sentry scripts we are using to monitor our service at form.trustmary.com?
I'm not sure what happened at trustmary.com but we have some analytics there too. Is that a problem?

**Comment by spirillen** [comment]
> @spirillen I'm with @kalliome and I can try to help you. What do you mean by "blocking privacy oriented connections"? Are you referring to Sentry scripts we are using to monitor our service at form.trustmary.com? I'm not sure what happened at trustmary.com but we have some analytics there too. Is that a problem?

You are blocking tor so I can't work with your domain, as you do not support #privacy. so until you  permits tor and respects the Right to freedom and privacy, you most wait to someone who doesn't care about democracy

**Comment by kalliome** [comment]
Hi @spirillen, thank you for informing us. We are not actively blocking Tor, but we are using Vercel and it might block some Tor exit nodes. I tried and after rerouting Tor, I was able to open our website. I tried opening other Vercel sites and they had same issue. 

Screenshot 2023-11-02 at 14 31 59

The reason we had to move to Vercel, is that when we were added to this list originally, Netlify banned our account without warning and without consulting us. We are a Finnish review management startup and we are not sharing malware and we will filter out any user we find that are using our services for phishing. 

So could you please try again and try to reroute Tor couple times?

**Comment by spirillen** [comment]
I can't keep wasting time on this unfriendly domain, allow ALL Tor before mention me again. I stop working on this domain until tor is allowed and freedom and privacy is respected

image

**Pull request merged**
