### PR TITLE
add safecartusa[.]com to add-wildcard-domain

### PR DESCRIPTION
**Pull request by g0d33p3rsec**
## Phishing Domain/URL/IP(s):

```
https://safecartusa.com/MzEzVjFINGE4eDFTM3c=
https://safecartusa.com/M1oyajZEMHEycTFDOW4=
https://safecartusa.com/M3cyUTVWOGU5VDVtM3Y=
https://safecartusa.com/M04zMjFZNFM4NjJ5MXQ=
https://safecartusa.com/M0MzeTFTNFo4ZDFVN0I=
https://safecartusa.com/MzIxVTJ1NjI3cTU0OTg=
https://safecartusa.com/310335047127.htm
https://safecartusa.com/310335024831.htm
https://safecartusa.com/310335010285.htm
https://safecartusa.com/3103350859508.htm
https://safecartusa.com/310335031336.htm
https://safecartusa.com/310335014615.htm
https://safecartusa.com/3103350025351.htm
https://safecartusa.com/310335000325.htm
https://safecartusa.com/3103350864188.htm
https://safecartusa.com/3103350408202.htm
https://safecartusa.com/module/31033508944.htm
https://safecartusa.com/module/3103350067287.htm
https://safecartusa.com/M04zVDFBM1Y5NjZCMk4=
https://safecartusa.com/M3UxdzMwMk8wWjJGMUw=
https://safecartusa.com/M3AyQjRSMnEwOTdzNm4= 
https://safecartusa.com/M2czTDExNFE2VTM1Nlg=
https://safecartusa.com/MnAzcDg1M3IyTjJGOEQ=
https://safecartusa.com/310335087960.htm
https://safecartusa.com/310335034417.htm
https://safecartusa.com/module/3103350898351.htm
https://safecartusa.com/module/3103350900103.htm
https://safecartusa.com/310335093442.htm
https://safecartusa.com/module/3103350408202.htm
https://safecartusa.com/3103350002303.htm
https://safecartusa.com/310335003687.htm 
https://safecartusa.com/3103350180117.htm
https://safecartusa.com/310335091777.htm
https://safecartusa.com/310335027812.htm
https://safecartusa.com/3103350103188.htm 
https://safecartusa.com/310335044828.htm
https://safecartusa.com/31033505011.htm
https://safecartusa.com/310335012540.htm
https://safecartusa.com/310335037019.htm
https://safecartusa.com/M0IyQjZNMm04aDU5Nzc=
https://safecartusa.com/M2kzQzBzNWkyRzBpMXQ=
https://safecartusa.com/MzMxQTNoMlcwZTJsMU8=
https://safecartusa.com/M0kzOTFOMkE2MTlMMWw=
https://safecartusa.com/M3QzWDFMNFEwbDZCNVk=
https://safecartusa.com/M24xRTdENkM2cjBlNDg=
https://safecartusa.com/M3EzRjFiMGEyQzRSNm8=
https://safecartusa.com/MzkyWTF4NzcySDVaODc=
https://safecartusa.com/M2kyNzhPMkU3SDhBOG4=
https://safecartusa.com/M3IzTDFKNkQ0VTB3NUE=
https://safecartusa.com/M0IyZzRVOWU2SjFKMWU=
https://safecartusa.com/Mm84VzdsMVcwQzVlMVQ= 
```

## Impersonated domain

```
https://www.ufs.ac.za/
https://ww1.ukzn.ac.za/
https://www.uwc.ac.za/
https://www.wits.ac.za/
https://www.wsu.ac.za/
https://facebook.com/
https://www.instagram.com/
https://www.snapchat.com/
https://twitter.com
https://ff.garena.com
https://www.betway.co.za
```

## Describe the issue

This domain is now hosting the phishing kit that was previously at foreverfarley[.]com (#387), azezieldraconous[.]com (https://github.com/mitchellkrogza/phishing/pull/381), westernautomobileassembly[.]com (https://github.com/mitchellkrogza/phishing/pull/376) , littleswanaircon[.]com[.]sg (https://github.com/mitchellkrogza/phishing/pull/372), iwan2travel[.]com(https://github.com/mitchellkrogza/phishing/pull/370 ), applesforfred[.]com (https://github.com/mitchellkrogza/phishing/pull/369), theaerie[.]ca (https://github.com/mitchellkrogza/phishing/pull/367), nico[.]sa (https://github.com/mitchellkrogza/phishing/pull/366), and ajstelecom[.]com[.]mx (https://github.com/mitchellkrogza/phishing/pull/362) 

### Screenshot

<details><summary>Click to expand</summary>

image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image

</details>

### CODE REVIEW

**Comment by g0d33p3rsec** [comment]
URIs on this domain have been returning 404s for a couple of days now.  I'll leave the PR open for the maintainers to do with as they please.  The activity group has moved to another host and can now be found at jestertunes[.]com (#393).
image

**Comment by spirillen** [comment]
I'll merge them, then [pyfunceble](https://github.com/funilrys/PyFunceble) will remove the dead once

**Comment by g0d33p3rsec** [comment]
> I'll merge them, then [pyfunceble](https://github.com/funilrys/PyFunceble) will remove the dead once

Thanks!  I wonder if pyfunceble may be causing the false negatives when I add as domain or wildcard.  When I first added by individual URI, Virus Total would return a positive once the commit was merged upstream.  Since, as I've been adding as domain or wildcard, the sites seem to be dropped by the time this repo is merged upstream resulting in subsequent false negatives on VT from the Phishing Database even though the upstream repo showed recent merges.  That's why I tried testing both a few commits ago but the results were inconclusive.  I should have more time to dig into it after the semester ends next week.  If you want to compare output, I've been trying to track the group using a VT collection which can be found at ```https://www.virustotal.com/gui/collection/5b7e996c553034dddc8c690ea6be0adb3182b0fa96ce6a8b29627e165fb47f38/iocs```


Here's an example from a recent add ```https://www.virustotal.com/gui/url/0503dbd260648c364c10793657cdebe883da30554b3c9cbed639025ea45e58e7```  Most of the detections shown are from hand feeding the domain to the individual EDR vendors, which can be a bit laborious. 
image
image

**Comment by spirillen** [comment]
That is an interesting observation, and for sure something this project should be following up on. But where to run the thread?... Allow me to think about this one for a while and I'll try to find the right locate for this question, but for you observation about @pyfunceble it should not be the issue when we are in the case of adding records, that could be a case while testing for removal of outdated records

**Comment by funilrys** [comment]
Interesting ... I'll have to investigate this too ... 
---
@/githubbot keep me updated.

**Comment by g0d33p3rsec** [comment]
> that could be a case while testing for removal of outdated records

I'm wondering what endpoints it tries to test if it only has the domain to work with and no specific URIs.  For most hosts, the root domain has been returning a default Apache/ Nginx page of the sort that comes with a fresh install.  The only exception that I can think of offhand is the deface that was done to westernautomobileassembly[.]com

**Comment by spirillen** [comment]
> > that could be a case while testing for removal of outdated records
> 
> I'm wondering what endpoints it tries to test if it only has the domain to work with and no specific URIs. For most hosts, the root domain has been returning a default Apache/ Nginx page of the sort that comes with a fresh install.

This is one of many reasons that PyFunceble by default leaves a record as `ACTIVE` if any test are positive and then disregards any other test results.

This is of course not the Holy Grail for how this should be handled, but as there isn't enough human resources to maintain and cats any scumbag URI out there, we have to cut some corners, also the fact of RFC:954 is limited to FQDN, it don't make a hole lot of seance to keep a URI list for all those running on the ~60 years old hosts file system or even the never RPZ. The only places you really can use URI systems are in browse addons like [Ublock Origin](https://github.com/gorhill/uBlock/) and proxy servers like [Squid](http://www.squid-cache.org/)

@/githubbot remind me

**Comment by g0d33p3rsec** [comment]
> This is one of many reasons that PyFunceble by default leaves a record as `ACTIVE` if any test are positive and then disregards any other test results.

Oh, that makes total sense and for an interesting problem.  I should only have a few more days of having to think in C++ before I can get back to thinking in Python and take a closer look at both projects.

**Comment by spirillen** [comment]
> URIs on this domain have been returning 404s for a couple of days now. I'll leave the PR open for the maintainers to do with as they please. The activity group has moved to another host and can now be found at `jestertunes.com` (#393).


@g0d33p3rsec As I do think about the 404 uri's from your list above, I can't think of any current process that actually would remove them from the project. Reason: we treats a 404 as a temporary brake in something bad, as you can see here: https://github.com/mitchellkrogza/phishing/blob/a6e8b7e87561fc4b4a8b4066d1d22f05ee0dd94e/.pyfunceble/.PyFunceble.overwrite.yaml#L69

So is there by any change that your code could run a automated test for this, or do I have to write up something (which I sucks at)

**Comment by spirillen** [comment]
> When the new records are being merged from this repo upstream, what checks are done to validate the current status?

To my knowledge, none, As I keeps this one as clean as the time allows me.

Which reminds me to set up a new test...

> Does it just convert the domain to an http or https request and evaluate the response looking for any non 500 code?

The `Does IT`, what is `it` you refer to here, as the answer may depends on who _it_ is

**Comment by spirillen** [comment]
Moved the workflow question to https://github.com/mitchellkrogza/phishing/issues/395

**Pull request merged**
