### PR TITLE
Update add-domain `sgp1.digitaloceanspaces.com`

### PR DESCRIPTION
**Pull request by WebworkrNet**
`https://sgp1.digitaloceanspaces.com/ontos-leasing/musterwohnung-hamburg.html`

`https://sgp1.digitaloceanspaces.com/ontos-leasing/ludwig-missionsverein.html`

## Domain/URL/IP(s) where you have found the Phishing:

email spam

## Impersonated domain

`commerzbank.de`

## Related external source

- https://www.virustotal.com/gui/domain/sgp1.digitaloceanspaces.com
- https://www.virustotal.com/gui/url/cd291be3f813a513e09470ae3780afd8c92d5ca5fa41c69322a4bb85b97277e1?nocache=1
- https://www.virustotal.com/gui/url/62f92ad573706446f6eefea5f85930df00df7247480f355312f8d64db58e6659?nocache=1

## Describe the issue

- Malicious
- Phishing

### Screenshot

Screenshot_20230821_053031_Firefox Nightly
Screenshot_20230821_053128_Firefox Nightly

Screenshot_20230821_053715_Firefox Nightly

<details><summary>Click to expand</summary>

</details>

### CODE REVIEW

**Comment by WebworkrNet** [comment]
**Sender**
`
Commerzbank 
Norpley90@commerzbank.net
`

**Reply.to**
`reply_to@opernhausblog.de`

**Subject**
`Wichtige Aktualisierungen: Sicherheit Ihrer Kontobestätigung  DE-76461`

**Body**
```
Sehr geehrter Kunde,

Wir möchten Sie über wichtige Aktualisierungen in der PhotoTan informieren, die für die Sicherheit Ihrer Kontobestätigung wichtig sind.

Bitte bestätigen Sie Ihre Kontobestätigung, indem Sie auf den folgenden Link klicken: 

 


[Klicken Sie hier](https://sgp1.digitaloceanspaces.com/ontos-leasing/ludwig-missionsverein.html)

 

Die Kontobestätigung ist erforderlich, um weiterhin problemlos auf Ihre commerzbank-Konten zugreifen zu können. 

Bitte beachten Sie, dass Ihre Kontobestätigung vorübergehend deaktiviert wird, falls Sie den Link nicht innerhalb von 7 Tagen öffnen.

In diesem Fall setzen Sie sich bitte mit unserem Kundensupport in Verbindung, um die Kontobestätigung erneut zu aktivieren.

Wir schätzen Ihre Zusammenarbeit bei dieser wichtigen Aktualisierung und stehen Ihnen bei Fragen oder Bedenken gerne zur Verfügung. 

Vielen Dank für Ihr Verständnis und Ihre Unterstützung.

Mit freundlichen Grüßen,

Commerzbank.

```

**Comment by WebworkrNet** [comment]
**Sender**
`
Commerzbank 
Norpley90@commerzbank.net
`

**Reply.to**
`reply_to@opernhausblog.de`

**Subject**
`Wichtige Aktualisierungen: Sicherheit Ihrer Kontobestätigung  DE-85684`

**Body**
```
Sehr geehrter Kunde,

Wir möchten Sie über wichtige Aktualisierungen in der PhotoTan informieren, die für die Sicherheit Ihrer Kontobestätigung wichtig sind.

Bitte bestätigen Sie Ihre Kontobestätigung, indem Sie auf den folgenden Link klicken: 

 


[Klicken Sie hier](https://sgp1.digitaloceanspaces.com/ontos-leasing/musterwohnung-hamburg.html)

 

Die Kontobestätigung ist erforderlich, um weiterhin problemlos auf Ihre commerzbank-Konten zugreifen zu können. 

Bitte beachten Sie, dass Ihre Kontobestätigung vorübergehend deaktiviert wird, falls Sie den Link nicht innerhalb von 7 Tagen öffnen.

In diesem Fall setzen Sie sich bitte mit unserem Kundensupport in Verbindung, um die Kontobestätigung erneut zu aktivieren.

Wir schätzen Ihre Zusammenarbeit bei dieser wichtigen Aktualisierung und stehen Ihnen bei Fragen oder Bedenken gerne zur Verfügung. 

Vielen Dank für Ihr Verständnis und Ihre Unterstützung.

Mit freundlichen Grüßen,

Commerzbank.

```

**Comment by WebworkrNet** [comment]
Thank you for merging.

Is that correct that the contents of this list are regularly included in [StevenBlack/hosts](https://github.com/StevenBlack/hosts) ?

**Comment by spirillen** [comment]
I can't tell as I do NOT  relay on this project is it is very faulty and unreliable as privacy/adware blacklists

**Comment by WebworkrNet** [comment]
I assumed this because [StevenBlack/hosts](https://github.com/StevenBlack/hosts) lists [mitchellkrogza/Badd-Boyz-Hosts ](https://github.com/mitchellkrogza/Badd-Boyz-Hosts ) as a source. 

Is [mitchellkrogza/phishing](https://github.com/mitchellkrogza/phishing) /  [mitchellkrogza/Phishing.Database/]( https://github.com/mitchellkrogza/Phishing.Database) part of Badd Boyz hosts?

**Comment by WebworkrNet** [comment]
Faulty and unreliable in what ways?

False positive and false negative?

Which lists do you trust?

**Comment by spirillen** [comment]
> Which lists do you trust?

Mine, as they do not makes any "Exceptions" for #bigtech  tracking is tracking and spyware is spyware, no matter who provides it

**Comment by WebworkrNet** [comment]
>  Pull request successfully merged and closed

> You’re all set — the WebworkrNet:main-3 branch can be safely deleted. 

Branch deleted.

**Comment by WebworkrNet** [comment]
> > Which lists do you trust?
> 
> Mine, as they do not makes any "Exceptions" for #bigtech tracking is tracking and spyware is spyware, no matter who provides it

@spirillen I don't fully understand your statement. Can you please explain them. In particular, the “not” is unclear to me in this context. That sounds contradictory to me. What are the exceptions for?

**Comment by spirillen** [comment]
@WebworkrNet 

My statement is:

--------

DO NOT trust or believe anything around StevenBlack and his project.
The majority of people there, DO NOT know what they are doing and SB don't understand RFC:952 & RFC:953, so how can he maintain a list that is meant to support RFC:952?
ALSO and here is the big fish :fish:, if something is "breaking" something else, it is removed, whitelisted (sorry allowlisted), regardless how devastating it is for IE. Privacy or tracking in general.
For example do you find any of the biggest spyware producer `google.com` or `maps.google.com` on any of his blacklists? nope, there are on his whitelist.
You can't trust his project, even he blames to, he is protecting people from just this, then the reality is, it is the opposed that is happening, ands everybody is exposed for #spyware, #Tracking and #adware from #bigtech.
The truth is also, he are not doing any work by him self, everything is dome by others, check for your self, he has never been writing any of the code, that is done by people like @funilrys and me (not any more as he has blocked me, after I reveled he does nothing by him self and don't understand RFC:952).
You can also notice, he don't like I spotted in a issue at https://github.com/clefspeare13/pornhosts that he know nothing about RFC:952 as he clearly do not understand the difference between `example.com` & `www.example.com`, by see he excluded the best maintained and precise #porn lists from his project: https://github.com/StevenBlack/hosts/commit/1c9548a2197c31ba55f136ed1b9508232b7834bd and stole the source code from my project after clefspeare13 handed over the project tp My Privacy DNS.
It is also a fact that StevenBlack kept steeling from my work at My Privacy DNS, by using @Sinfonietta as proxy for "importing" my work into his project; yes that lists of CopyRight violation against those two, are very very long and many reports have been send to #GH
The answer to your question `False positive and false negative?` regarding SB's #hosts lists vs hos statement about the project is... **false negative**'s in a bunch, as it completely fails to protect users against anything useful.

--------

Hoping this helps giving you some clarity, if not, please just ask again.

**Pull request merged**
