### PR TITLE
add cliphot-portugal-vip.xyz

### PR DESCRIPTION
**Pull request by Zachinquarantine**
**⚠️ WARNING: THIS SITE CONTAINS NSFW/ADULT CONTENT, AS WELL AS PHISHING ⚠️**
Facebook phish, click on the fake play button for a fake login page to appear...
from https://forums.malwarebytes.com/topic/276196-facebook-phishing/
hxxps://cliphot-portugal-vip.xyz/

### CODE REVIEW

**Comment by spirillen** [comment]
Hmm I get this straight up both with and without uBlock Origin activated...

No play button.

image

**Comment by Zachinquarantine** [comment]
yes, that's the scam. That login popup is phishing...

**Comment by Zachinquarantine** [comment]
also: do I have to rebase anything or is that automatic?

**Comment by spirillen** [comment]
This means rebase....

image

You learn to rebase from remote master into local branch from the beginning, I know GH have made a bottom to do this (sometimes) but do it the right way, this will help you when the contributions are getting a bit more complexes :smiley: 

I've made a 5 steps guide to my self, when I had to learn the ropes of merging origin in: https://mypdns.org/spirillen/PyFunceble/-/issues/11

Credit to: @funilrys

**Comment by spirillen** [comment]
Hmm your malware link seems outdated..

<details><summary>Click to unfold</summary>


image

</details>

**Comment by Zachinquarantine** [comment]
> 
> 
> Hmm your malware link seems outdated..
> Click to unfold
> 
> image

slika

**Comment by spirillen** [comment]
Thanks, then it just the rebase :smiley: :arrow_double_up:

**Comment by Zachinquarantine** [comment]
I think I fixed it..?

**Comment by Zachinquarantine** [comment]
yup, appears to be fixed

**Comment by Zachinquarantine** [comment]
since I'm lazy, I figured out [how to do it on the GitHub GUI](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) lmao

**Comment by spirillen** [comment]
> since I'm lazy, I figured out [how to do it on the GitHub GUI](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) lmao

That is actually not lazy.... it will bite you tenfold later, when you have a real merge conflict.... not just 2 lines in a blacklist, why I gave you the link above. When yo have learned and understood what is happening, then you could use the "I'm Feeling I'm a lucky punk" (Dirty Harry, Do you feel lucky punk?) tool

**Comment by Zachinquarantine** [comment]
> 
> 
> > since I'm lazy, I figured out [how to do it on the GitHub GUI](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) lmao
> 
> That is actually not lazy.... it will bite you tenfold later, when you have a real merge conflict.... not just 2 lines in a blacklist, why I gave you the link above. When yo have learned and understood what is happening, then you could use the "I'm Feeling I'm a lucky punk" (Dirty Harry, Do you feel lucky punk?) tool

I definitely will in the future, but right now my Git install is super broken and I'm tired so... idk

**Comment by spirillen** [comment]
:laughing: 

use git from repo.... https://git-scm.com/download/linux or there repo and build t your self 

```shell
git clone https://github.com/git/git
```

**Pull request merged**
