### PR TITLE
Update add-wildcard-domain to include brunotasso.com.br

### PR DESCRIPTION
**Pull request by g0d33p3rsec**
## Phishing Domain/URL/IP(s):

```
https://brunotasso.com.br/M2EyVjlyOWozeDRNOG8=
https://brunotasso.com.br/M1czbDc0M1U5ajN4OWE=
https://brunotasso.com.br/M3kzWDdjMEg3azZFMW8=
https://brunotasso.com.br/M0kzaTdJMUQxUTdlMUM=
https://brunotasso.com.br/M3ozTTdQMm4wUTBkNTM=
https://brunotasso.com.br/M1EyNTNUOWowcDJOMnY=
https://brunotasso.com.br/M0cxMzN1M1g5czQzNkI=
https://brunotasso.com.br/M28zcDdzN2MxYzd3MkY=
https://brunotasso.com.br/M2IzRjc0MkwweThyNjU=
https://brunotasso.com.br/M2oyeDRlN1Q0ZDREOXY=
https://brunotasso.com.br/Mkc5QzNVNzA1NTg2OVM=
https://brunotasso.com.br/MzczNjdEM0gwRTBGN1Y=
https://brunotasso.com.br/M1YwbDhjMkgyaTI5OVY=
https://brunotasso.com.br/MlA4YTh5Mmo2UTZZNEo=
https://brunotasso.com.br/M1MzejdLM0QwZjIzMXk=
https://brunotasso.com.br/M28zajdzMzE0WTA1NFU=
https://brunotasso.com.br/MU0wdDc5MGg3UzdWMlk=
https://brunotasso.com.br/M2MzTzRUMnM3VzZFNUo=
https://brunotasso.com.br/M0UyaTNwNjA0bTl5NW4=
https://brunotasso.com.br/M1QzVTdSNmk0czVyNVQ=
https://brunotasso.com.br/M3kzazdpNmg2WTlvM24=
https://brunotasso.com.br/MmE4VDdIN1AwcThkMFE=
https://brunotasso.com.br/MzcyaDRLMGUwbjdZN04=
https://brunotasso.com.br/M1AzWDdlNlk4ejExOEg=
https://brunotasso.com.br/M3IzUzdLNlQ5SDg2MHM=
https://brunotasso.com.br/M2czcDJyMHA5QTdiOXI=
https://brunotasso.com.br/M2wxVjB5OE83TjFOMEo=
https://brunotasso.com.br/M3IyTTlhOVozTjQ0OEs=
https://brunotasso.com.br/M3YzZjN3NTY3WDE2M1A=
```

## Impersonated domain

```
https://ff.garena.com/
https://www.betway.co.za
https://www.tut.ac.za/
https://www.wsu.ac.za/
```

## Describe the issue

This domain is now hosting the phishing kit that was previously at cantabriaeventos[.]com, wisbechguide[.]uk, pescacancun[.]com, bkengineersindia[.]com, englishplusmore[.]com, carnesboinobre[.]com[.]br, technowide[.]com[.]tr, jestertunes[.]com, safecartusa[.]com, foreverfarley[.]com, azezieldraconous[.]com, westernautomobileassembly[.]com, littleswanaircon[.]com[.]sg, iwan2travel[.]com, applesforfred[.]com, theaerie[.]ca, nico[.]sa, ajstelecom[.]com[.]mx, and many others (approximately 120 domains since 2021).

### Screenshot

<details><summary>Click to expand</summary>

image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image

</details>

### CODE REVIEW

**Comment by g0d33p3rsec** [comment]
Evidence of the domain being used for smishing.
Source: ```https://x.com/mrsPatiencebet/status/1802270332507578662```
GQLzTk2WYAAWxV2
GQLzg54XIAA-0ep

**Comment by spirillen** [comment]
> smishing

:rofl: :smile:

**Comment by spirillen** [comment]
By the way, how did your exam goes with the C++ project

**Comment by g0d33p3rsec** [comment]
> smishing

I know, I hate the term too, but try to stick to the standard language (there's also vishing and, most recently, quishing).  Personally, I think phishing is phishing just as spam is spam but what do I know, I'm just a baby brained undergrad.

  > By the way, how did your exam goes with the C++ project

  I finished with an A, thanks for asking.  Some things could have been better but I'm finally learning that at the end of the semester it all looks the same on my transcript.  I am looking forward to getting back to Python when I need to script something though.  I'm not a big fan of footguns.

**Comment by g0d33p3rsec** [comment]
There's even a [quishing](https://www.slideshare.net/MITREATTACK/the-case-for-quishing) card in the Red Canary [Backdoors & Breaches](https://www.blackhillsinfosec.com/projects/backdoorsandbreaches/) expansion deck.
If it were just an exam body that insisted on the term, I would probably avoid it.  Considering it is included in the [ATT&CK entry for phishing](https://attack.mitre.org/techniques/T1660/), I'll entertain the terms as long as using them adds clarity. 

IMG_20240616_175915826(1)

**Comment by spirillen** [comment]
>  I am looking forward to getting back to Python

Stick to C++ and Rust, python is heavy and uses a lot of resources compared to C, C++ and Rust

> There's even a quishing card in the Red Canary Backdoors & Breaches expansion deck

Seriously? shall I really start to study new term's for something we already have nice stinking dead animals too... :fishsticks:

**Comment by g0d33p3rsec** [comment]
> python is heavy and uses a lot of resources compared to C, C++ and Rust

but it is essentially the lingua franca of infosec.  I like being able to read C and related languages for reversing purposes but I am an analyst and not a developer.  

> shall I really start to study new term's for something we already have nice stinking dead animals too...

I wouldn't put much effort into it.  I'm only mindful of the terms because I'm moving towards CTI as a specialty and the ATT&CK matrix is a common way to communicate indicators.  There's not much I can do with it with regard to this activity group due to my limited visibility.  If I had a view into their other post compromise activities, I would have probably published a report and given them some sort of Fuzzy Ducky name like the vendors do but, alas, I just track them as "unknown phishing kit".

**Comment by g0d33p3rsec** [comment]
and for the latest "well that was interesting," a broken redirect has led to a Russian TLD.
```https://urlscan.io/result/38c7f97b-57e7-4d66-8ce6-3d42ee945bb5/#transactions```
image
```
dig brunotasso.com.br @8.8.8.8 +trace                                                                           9 ↵

; <<>> DiG 9.18.24-0ubuntu0.22.04.1-Ubuntu <<>> brunotasso.com.br @8.8.8.8 +trace
;; global options: +cmd
.                       87203   IN      NS      b.root-servers.net.
.                       87203   IN      NS      m.root-servers.net.
.                       87203   IN      NS      j.root-servers.net.
.                       87203   IN      NS      l.root-servers.net.
.                       87203   IN      NS      g.root-servers.net.
.                       87203   IN      NS      c.root-servers.net.
.                       87203   IN      NS      i.root-servers.net.
.                       87203   IN      NS      f.root-servers.net.
.                       87203   IN      NS      e.root-servers.net.
.                       87203   IN      NS      h.root-servers.net.
.                       87203   IN      NS      a.root-servers.net.
.                       87203   IN      NS      d.root-servers.net.
.                       87203   IN      NS      k.root-servers.net.
.                       87203   IN      RRSIG   NS 8 0 518400 20240630050000 20240617040000 5613 . WIpw8Imnu5OTSNTzS/tfghXFZg9JelCPOt7A8UQ8cKTJG35i3zvadCae /XCIZcZ+8P8bcfvxTgmuqOQOYjMVdGtSulPABnww6n3fN9WRWkvXnqen EK2kWeLWJ/4kuem3cxbx/tH/s82y50npXkZhPwvt7T0c0y4vSf+UPxMe N+2w5/a+tG1JD8sbswcTrPRP4wyjdBJasz4kdHyi1SO3GqJ827mH/E2D CNGD/1aX4r9On3siIbj8XbfHKbsLaraNAGwwYSwAsjwEEHUGh56/7yoP wOUjhXbbTItuXMBLHh53tRHBG6vXQS2O6qckWUp9+3khSrFiSnFvtkKL 7yq+yQ==
;; Received 525 bytes from 8.8.8.8#53(8.8.8.8) in 0 ms

br.                     172800  IN      NS      a.dns.br.
br.                     172800  IN      NS      b.dns.br.
br.                     172800  IN      NS      c.dns.br.
br.                     172800  IN      NS      d.dns.br.
br.                     172800  IN      NS      e.dns.br.
br.                     172800  IN      NS      f.dns.br.
br.                     86400   IN      DS      38298 13 2 9F2D4993F47B0F2751DE0007D70A2754EE532FE373761154D9EA7A8C B9D8EA18
br.                     86400   IN      RRSIG   DS 8 1 86400 20240630050000 20240617040000 5613 . aEqum3YFZoLCOPkmjtBuAklSjh/bEHgW+PlwdvKVN6gkhy4cfdJTYNG1 uosjfvMUoJ6tQ+3UD0q6rCvMxlqzNo4TdQ7Ohvp5HB9Sc4HhySRLGIS9 xpPtr5KPuCTLBLIjEhMN79Y95Czw8iT7yiWqZA4ohIslokblvwiGu20M Oel5NwjkOTcXC01c1g0HmozZS1TZFb7gW/qo7MrHQcchUYlXBjYa6R1P F41a8Ihr66cwtVbw+Nk6g/oeiX6GSUAnkdPyiGaCCY71ZUpQ3aRxLZ1L EhUfQARGPDZsWqc12x/HXSlsHZ/V4Ot32eAUH3+u5SRxHLwDZOs1zz1p mhjAxg==
;; Received 745 bytes from 192.5.5.241#53(f.root-servers.net) in 19 ms

;; UDP setup with 2001:12f8:8::10#53(2001:12f8:8::10) for brunotasso.com.br failed: network unreachable.
;; no servers could be reached

;; UDP setup with 2001:12f8:8::10#53(2001:12f8:8::10) for brunotasso.com.br failed: network unreachable.
;; no servers could be reached

;; UDP setup with 2001:12f8:8::10#53(2001:12f8:8::10) for brunotasso.com.br failed: network unreachable.
brunotasso.com.br.      3600    IN      NS      ns917.hostgator.com.br.
brunotasso.com.br.      3600    IN      NS      ns916.hostgator.com.br.
3jjae7tuh25kfuu185hpof94omjk2t8u.com.br. 900 IN NSEC3 1 1 0 E06550395A4A6EBF717E 3JJALNAUBH4VGPGVOO7KJJ2AMUVKJSH9 NS SOA RRSIG DNSKEY NSEC3PARAM
3jjae7tuh25kfuu185hpof94omjk2t8u.com.br. 900 IN RRSIG NSEC3 13 3 900 20240701152012 20240617142012 57609 com.br. BhMEOojcSEb+6QAx4CLaTVEqYhmQpVyfuMk8kkrc8Ox0LarB8IB6Fadu 3J/CQFLjmlUXDwelVAH+olanwDH6bQ==
a11cjq97ru0j940tson9cbqj4vt9edt4.com.br. 900 IN NSEC3 1 1 0 E06550395A4A6EBF717E A11D49RA68NNDU58C0BV88BTLCR5V4HD NS DS RRSIG
a11cjq97ru0j940tson9cbqj4vt9edt4.com.br. 900 IN RRSIG NSEC3 13 3 900 20240625170512 20240611160512 57609 com.br. 6qtxBBLrq/V1F/E2Zkv4NQ/3rWElrJAW+KFZbMKplKbUxmIxBgZ8jjh4 FqlzdoP9hi/LRBUxmlRb6IVPZ2GbzQ==
;; Received 513 bytes from 200.229.248.10#53(e.dns.br) in 109 ms

brunotasso.com.br.      14400   IN      A       162.241.2.87
brunotasso.com.br.      86400   IN      NS      ns917.hostgator.com.br.
brunotasso.com.br.      86400   IN      NS      ns916.hostgator.com.br.
;; Received 172 bytes from 162.241.2.86#53(ns917.hostgator.com.br) in 29 ms
```


```
curl -v https://brunotasso.com.br/M1czOThkOE85bTl2MDE\=                                                         
*   Trying 162.241.2.87:443...
* Connected to brunotasso.com.br (162.241.2.87) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.brunotasso.com.br
*  start date: Jun  8 22:29:16 2024 GMT
*  expire date: Sep  6 22:29:15 2024 GMT
*  subjectAltName: host "brunotasso.com.br" matched cert's "brunotasso.com.br"
*  issuer: C=US; O=Let's Encrypt; CN=R11
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* Using Stream ID: 1 (easy handle 0x56050c8fbeb0)
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET /M1czOThkOE85bTl2MDE= HTTP/2
> Host: brunotasso.com.br
> user-agent: curl/7.81.0
> accept: */*
>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
< HTTP/2 301
< location: http://srv214734.hoster-test.ru/sure-authentication-performance/index.htmlindex3.php?vino=M1czOThkOE85bTl2MDE=
< content-length: 318
< content-type: text/html; charset=iso-8859-1
< date: Mon, 17 Jun 2024 15:25:20 GMT
< server: Apache
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://srv214734.hoster-test.ru/sure-authentication-performance/index.htmlindex3.php?vino=M1czOThkOE85bTl2MDE=">here</a>.</p>
</body></html>
* Connection #0 to host brunotasso.com.br left intact
```

**Comment by g0d33p3rsec** [comment]
I'll just leave this here in case someone else wants to dig into it before I have time to investigate.  It looks like the slip up revealed other phishing related infrastructure.

```https://urlscan.io/ip/31.28.24.131```
2fb62c16-ee96-4336-aae6-449fc8fd9071
631c0884-9aa0-4225-a5f1-9c86554d599c

**Pull request merged**
